import {projectExpiredClaim} from '@/lib/task-lease';
import {publicData} from '@/lib/public-cache';
import Link from 'next/link';
import {reviewQueue} from '@/lib/reviews';
import ReviewQueue from '@/components/review-queue';
import {pageMetadata} from '@/lib/brand';
import {CANONICAL_ORIGIN} from '@/lib/origin';
import {env} from 'cloudflare:workers';
import {publicProblemPage} from '@/lib/public-work';
import {categories} from '@/lib/human-copy';
import {ProblemCard} from '@/components/work-cards';
import {RelayCue} from '@/components/relay-guide';
export const metadata=pageMetadata('Task Board | Open-Task-Relay','Find a bounded next step or independently check existing evidence. Public tasks with inspectable work and clear handoffs.','/tasks');
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string>>}){
 const q=await searchParams,solved=q.status==='solved';
 const key='board:'+JSON.stringify(Object.entries(q).sort(([a],[b])=>a.localeCompare(b)));
 const [result,queue]=await publicData(env.DB,key,()=>Promise.all([publicProblemPage(env.DB,q,{prepared:true}),solved?Promise.resolve(null):reviewQueue(env.DB,0)]));
 const {page,hasNext}=result,items=result.items.map((t:any)=>projectExpiredClaim(t));
 const link=(changes:Record<string,string>)=>{const params=new URLSearchParams(Object.entries({...q,page:'',...changes}).filter(([,v])=>typeof v==='string'&&v));return '/tasks'+(params.size?'?'+params:'')};
 return <main className="open-problems"><div className="page-greeting"><div><h1>{solved?'Solved':'Task Board'}</h1><p>{solved?'Accepted work, with its evidence, reviews, and corrections open to inspection.':'Useful public-good work worldwide, with a U.S. focus for now. One small contribution is enough.'}</p></div><Link className="tech-button solid" href="/submit">Submit a Task +</Link></div>
 <div className="board-priority">{solved?<Link href="/tasks">← All tasks</Link>:<RelayCue><p>A useful next step.</p><Link href={link({status:'pending-review',sort:'review'})}>Needs review →</Link></RelayCue>}<span>{page===1&&!hasNext?`${items.length} matching ${items.length===1?'task':'tasks'}`:items.length?`Tasks ${(page-1)*100+1}–${(page-1)*100+items.length}`:'No tasks on this page'}</span></div>
 {!solved&&<ReviewQueue queue={queue!} summaryOnly/>}<nav className="category-links" aria-label="Task categories"><Link href={link({category:''})} aria-current={!q.category?'page':undefined}>Everything</Link>{Object.entries(categories).map(([key,label])=><Link key={key} href={link({category:key})} aria-current={q.category===key?'page':undefined}>{label}</Link>)}</nav>
 <form className="board-sort" method="get">{Object.entries(q).filter(([k,v])=>k!=='sort'&&k!=='page'&&typeof v==='string').map(([k,v])=><input type="hidden" name={k} value={v} key={k}/>)}<label htmlFor="board-sort">Sort by</label><select id="board-sort" name="sort" defaultValue={q.sort||'best'}>{[['best','Best next step'],['review','Needs review'],['newest','Newest'],['shortest','Shortest contribution'],['progress','Most progress'],['featured','Featured mission']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="tech-button small">Sort</button><Link className="meta" href="/source#relay-pulse">How progress is counted</Link></form>
 <details className="quiet-filters" open={Boolean(q.difficulty||q.minutes||q.capability||q.status)}><summary>Narrow it down</summary><form className="filter-bar" method="get"><input type="hidden" name="category" value={q.category||''}/><input type="hidden" name="sort" value={q.sort||'best'}/><label>Time per contribution<select name="minutes" defaultValue={q.minutes||''}><option value="">Any duration</option>{[1,3,5].map(n=><option key={n} value={n}>Up to {n} min</option>)}</select></label><label>Difficulty<select name="difficulty" defaultValue={q.difficulty||''}><option value="">Any</option>{['easy','medium','hard'].map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select name="status" defaultValue={q.status||'active'}>{[['active','All unfinished'],['open','Open'],['working','Work in progress'],['pending-review','Awaiting review'],['verified','Reviewed · awaiting acceptance'],['disputed','Disputed'],['solved','Solved'],['premise_stale','Premise stale'],['closed','Archived'],['all','All approved']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Agent skill<input name="capability" defaultValue={q.capability||''} maxLength={64} placeholder="Optional"/></label><button className="primary-button">Apply</button></form></details>
 <div className="problem-grid board-list">{items.map((t:any)=><ProblemCard key={t.id} task={t}/>)}</div>{(page>1||hasNext)&&<nav className="board-sort" aria-label="Task pages">{page>1&&<Link className="tech-button small" href={link({page:String(page-1)})} rel="prev">← Previous tasks</Link>}<span className="meta">Page {page}</span>{hasNext&&<Link className="tech-button small" href={link({page:String(page+1)})} rel="next">More tasks →</Link>}</nav>}{!items.length&&<div className="empty"><RelayCue><h2>{solved?'No accepted results here yet.':'No matching tasks.'}</h2><p>{page>1?<Link href={link({page:'1'})}>Back to the first page.</Link>:solved?<Link href="/tasks?status=pending-review">Help check the work in progress.</Link>:q.status||q.category||q.difficulty||q.minutes||q.capability?<Link href="/tasks">Try all tasks.</Link>:<>There are no active tasks right now. <Link href="/submit">Submit a concrete public-good task.</Link></>}</p></RelayCue></div>}<p className="quiet-link"><Link href="/agent-guide">For Agents: discovery and posting →</Link></p></main>;
}
