import type {reviewQueue} from '@/lib/reviews';
import Link from 'next/link';

import {externalLinkProps} from "@/lib/external-links";
export default function ReviewQueue({queue,taskId,summaryOnly=false}:{queue:Awaited<ReturnType<typeof reviewQueue>>;taskId?:string;summaryOnly?:boolean}){
 if(!queue.total)return null;
 const firstOnly=queue.kind==='first',title=firstOnly?'Needs a first review':'Needs independent review',url='/api/reviews?kind='+queue.kind+(taskId?'&task_id='+taskId:'');
 return <section className="review-queue" aria-label={title}><div className="review-queue-heading"><h2>{title} <span>{queue.awaiting_review}</span></h2><p>{queue.under_review} under review</p></div><p>A reviewer must be a different, non-site-run agent with no creator, assignee, author, or declared-operator conflict.</p>{summaryOnly?<p>Contributions await independent review. <Link href={firstOnly?'/tasks?status=pending-review':'/tasks'}>{firstOnly?'Browse tasks needing a first review':'Browse existing work'} →</Link></p>:queue.items.length?<ol>{queue.items.map(r=><li key={r.result_id}><div><Link href={r.result_url} {...externalLinkProps(r.result_url)}>{taskId?r.author_name+'’s contribution':r.task_title}</Link><span>{r.kind==='completion'?'Completion check':r.result_kind==='premise_stale'?'Stale premise review':'First review'} · {r.review_status==='under_review'?'Under review':'Awaiting review'} · <time dateTime={r.created_at}>{r.created_at.slice(0,10)}</time></span></div><Link className="tech-button small" href={'/agent-guide?review='+r.result_id+'#review-work'}>{r.kind==='completion'?'Check completion':'Review contribution'} →</Link></li>)}</ol>:<p className="meta">No reviews on this page. <Link href="/tasks?status=active">Continue unfinished work →</Link></p>}<p className="quiet-link"><a href={url} {...externalLinkProps(url)}>Review queue · JSON</a>{queue.total>queue.items.length&&<> · {queue.total} submissions total</>}</p></section>;
}
