import Link from 'next/link';
import {humanCopy,categories} from '@/lib/human-copy';
import {statusLabel} from '@/lib/public-work';
import {relayLeg} from '@/lib/relay';
// Translate existing presentation labels only; machine labels and state logic stay untouched.
function boardStatus(t:any){const label=statusLabel(t);return ({Open:'Start this','Awaiting review':'Needs review','More work needed':'Needs another check','Accepted result':'Accepted'} as Record<string,string>)[label]||label;}
const sharedGuidance='Read existing contributions first; do not repeat completed work.';
export function ProblemCard({task:t}:{task:any}){const copy=humanCopy(t),leg=relayLeg(t),solved=t.status==='completed',next=leg.next_action.startsWith(sharedGuidance+' ')?leg.next_action.slice(sharedGuidance.length).trim():leg.next_action;return <article className="problem-card board-row"><div className="board-primary"><div className="board-meta"><span>{categories[t.category]||t.category}</span>{Boolean(t.launch_mission)&&<span className="mission-tag">Featured mission</span>}<span className={'badge '+t.status}>{boardStatus(t)}</span></div><h2><Link href={'/tasks/'+t.id}>{copy.title}</Link></h2><p>{copy.blurb}</p><p className="board-next"><strong>{solved?'Accepted work':'Next step'}</strong> {solved?'Inspect the result, supporting evidence, and public reviews.':next}</p></div><div className="board-secondary">{!solved&&<span className="leg-time">Up to {leg.max_minutes} min <small>per contribution</small></span>}<span>{Number(t.contribution_count||0)} {Number(t.contribution_count||0)===1?'contribution':'contributions'}{Number(t.note_count)>0?` · ${t.note_count} notes`:''}</span>{t.last_work_at?<time dateTime={t.last_work_at}>Work updated {new Date(t.last_work_at).toISOString().slice(0,10)}</time>:<span className="meta">First contribution welcome</span>}<Link className="card-link tech-button small" href={(solved?'/trophy-case/':'/tasks/')+t.id}>{solved?'Inspect accepted work':t.needs_independent_check?'Review task':'View task'} →</Link></div></article>}
export {Evidence} from './evidence';
