
import {externalLinkProps} from "@/lib/external-links";
import {publicData} from '@/lib/public-cache';
import Link from 'next/link';
import {pageMetadata} from '@/lib/brand';
import {env} from 'cloudflare:workers';
import {publicActivity,activityLabel,groupActivity} from '@/lib/activity';
import {RelayCue} from '@/components/relay-guide';
import {activityDate,activityPreview,activityTitle} from '@/lib/activity-copy';
import './activity.css';
export const metadata=pageMetadata('Public activity | Open-Task-Relay','Contributions, evidence checks and site operations, with their provenance kept visible.','/activity');
const filters=[['contributions','Contributions'],['reviews','Reviews'],['accepted','Accepted work'],['operations','Site operations'],['all','All activity']];
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string>>}){
 const q=await searchParams,filter=filters.some(([v])=>v===q.filter)?q.filter:'contributions',offset=Math.max(0,Math.min(100000,Number(q.offset)||0));
 // Message excerpts must reflect moderation immediately, including across isolates.
 const page=['all','operations'].includes(filter)?await publicActivity(env.DB,filter,offset):await publicData(env.DB,'activity:'+filter+':'+offset,()=>publicActivity(env.DB,filter,offset)),groups=groupActivity(page.items);
 function record(e:any){const summary=e.kind==='operation'?e.summary.replace(/^owner verification failed: /,'More work needed: '):e.summary;return <article className="activity-record" id={'activity-'+e.id}><div className="activity-record-top"><span className={'work-origin '+(e.managed?'site-work':e.eligible?'independent-work':'')}>{activityLabel(e)}</span><time dateTime={e.created_at} title={e.created_at+' (UTC)'}>{activityDate(e.created_at)}</time></div><h3><Link href={e.url} {...externalLinkProps(e.url)}>{activityTitle(e)}</Link></h3><p className="activity-byline">{e.actor_name||'Site moderation'}{e.managed&&e.kind==='contribution'?' · Site-run work, not independent verification.':''}</p><p className="activity-preview">{activityPreview(summary)}</p><Link className="activity-record-link" href={e.url} {...externalLinkProps(e.url)}>{e.kind==='accepted'?'Read accepted result':'Read full record'}</Link></article>}
 return <main className="prose activity-page"><h1>Follow the work.</h1><p className="activity-intro">Contributions, reviews, accepted results—and the corrections along the way.</p><nav className="activity-filters" aria-label="Activity filters"><div className="activity-primary-filters">{filters.slice(0,3).map(([v,l])=><Link className="tech-button small" key={v} href={'/activity?filter='+v} aria-current={filter===v?'page':undefined}>{l}</Link>)}</div><div className="activity-secondary-filters">{filters.slice(3).map(([v,l])=><Link key={v} href={'/activity?filter='+v} aria-current={filter===v?'page':undefined}>{l}</Link>)}</div></nav>{groups.length?<ol className="activity-list">{groups.map(g=><li key={g.key}>{record(g.items[0])}{g.items.length>1&&<details className="activity-group"><summary>{g.items.length-1} more {g.items[0].kind==='operation'?'site operations':'contributions'} from this day</summary>{g.items.slice(1).map(e=><div key={e.id}>{record(e)}</div>)}</details>}</li>)}</ol>:<div className="empty"><RelayCue><h2>{filter==='reviews'?'No reviews recorded yet.':'No records in this view yet.'}</h2><p><Link href={filter==='reviews'?'/tasks?status=pending-review':'/tasks'} {...externalLinkProps(filter==='reviews'?'/tasks?status=pending-review':'/tasks')}>{filter==='reviews'?'Find work that needs a review':'Browse tasks'}</Link></p></RelayCue></div>}{page.next_offset!==null&&<Link className="tech-button" href={`/activity?filter=${filter}&offset=${page.next_offset}`} {...externalLinkProps(`/activity?filter=${filter}&offset=${page.next_offset}`)}>Older records</Link>}<p className="meta activity-footnote">Previews use recorded text. Full records retain failures and corrections. Site-run work and simulations are labeled. <Link href="/source#relay-pulse">How activity is counted</Link></p></main>;
}
