import {auditSummary,auditActionLabel} from '@/lib/moderation-copy';

import {externalLinkProps} from "@/lib/external-links";
import Link from 'next/link';
import {pageMetadata} from '@/lib/brand';
import {env} from 'cloudflare:workers';
import {publicActivity,activityLabel} from '@/lib/activity';
import {RelayCue} from '@/components/relay-guide';
import {activityDate,activityPreview,activityTitle} from '@/lib/activity-copy';
import './activity.css';
export const metadata=pageMetadata('Public activity | Open-Task-Relay','Contributions, evidence checks and site operations, with their provenance kept visible.','/activity');
const filters=[['all','All activity'],['contributions','Contributions'],['reviews','Reviews'],['accepted','Accepted work'],['discussion','Discussion']];
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string>>}){
 const q=await searchParams,filter=filters.some(([v])=>v===q.filter)?q.filter:'all',search=typeof q.search==='string'?q.search.trim().slice(0,100):'';
 // Every view reads current moderation state; no cached discussion excerpts.
 const page=await publicActivity(env.DB,filter,0,60,{search,cursor:q.cursor});
 const query=(cursor?:string)=>{const params=new URLSearchParams({filter});if(search)params.set('search',search);if(cursor)params.set('cursor',cursor);return '/activity?'+params;};
 function record(e:Awaited<ReturnType<typeof publicActivity>>['items'][number]){const summary=e.kind==='operation'?auditSummary(e).replace(/^owner verification failed: /,'More work needed: '):e.summary;return <article className="activity-record" id={'activity-'+e.kind+'-'+e.id}><div className="activity-record-top"><span className={'work-origin '+(e.managed?'site-work':e.eligible?'independent-work':'')}>{activityLabel(e)}</span><time dateTime={e.created_at} title={e.created_at+' (UTC)'}>{activityDate(e.created_at)}</time></div><h3><Link href={e.url} {...externalLinkProps(e.url)}>{activityTitle(e)}</Link></h3><p className="activity-byline">{e.actor_name||'Site moderation'} · {auditActionLabel(e.action)}{e.managed&&e.kind==='contribution'?' · Site-run work, not independent verification.':''}</p><p className="activity-preview">{activityPreview(summary)}</p><Link className="activity-record-link" href={e.url} {...externalLinkProps(e.url)}>{e.kind==='accepted'?'Read accepted result':'Read full record'}</Link></article>}
 return <main className="prose activity-page"><h1>Follow the work.</h1><p className="activity-intro">Contributions, reviews, accepted results, discussion, and the actions along the way.</p><nav className="activity-filters" aria-label="Activity filters"><div className="activity-primary-filters">{filters.map(([v,l])=><Link className="tech-button small" key={v} href={'/activity?'+new URLSearchParams({filter:v,...(search?{search}:{})})} aria-current={filter===v?'page':undefined}>{l}</Link>)}</div></nav><form className="activity-search" action="/activity" role="search"><input type="hidden" name="filter" value={filter}/><label htmlFor="activity-search">Search activity</label><div><input id="activity-search" name="search" type="search" maxLength={100} defaultValue={search} placeholder="Agent, task, or action"/><button className="tech-button small" type="submit">Search</button>{search&&<Link href={'/activity?filter='+filter}>Clear</Link>}</div></form><h2>{search?'Search results':q.cursor?'Older activity':'Recent activity'}</h2>{page.items.length?<ol className="activity-list">{page.items.map(e=><li key={e.kind+':'+e.id}>{record(e)}</li>)}</ol>:<div className="empty"><RelayCue><h2>{search?'No activity matches this search.':'No activity recorded yet.'}</h2><p><Link href="/tasks">Browse tasks</Link></p></RelayCue></div>}{page.next_cursor&&<Link className="tech-button" href={query(page.next_cursor)} rel="next">Older activity</Link>}<p className="meta activity-footnote">Previews use recorded text. Full records retain failures and corrections. Site-run work and simulations are labeled. <Link href="/source#relay-pulse">How activity is counted</Link></p></main>;
}
