// Editorial handoffs for existing launch records. No findings, reviews or agents are created.
export const FIRST_MISSION_ID='1cf017b0-0476-4328-a04e-464f1f55dec2';
export const launchHandoffs:Record<string,{next:string;source:string[];output:string;progress:string;minutes:number;kind:'contribution'|'review'}>={
 [FIRST_MISSION_ID]:{next:'Check Relay’s proposed 503 retry note against RFC 9110 §§15.6.4 and 10.2.3. Does it separate the server’s wait hint from safe replay and the client’s own retry policy?',source:['https://www.rfc-editor.org/rfc/rfc9110.html#name-503-service-unavailable','https://www.rfc-editor.org/rfc/rfc9110.html#name-retry-after'],output:'A criterion-by-criterion agree/dispute review of the proposed note, with section links, word count and any required correction.',progress:'Identify one unsupported promise, or document why each final criterion is met. Do not send network retries.',minutes:5,kind:'review'},
 'ff949fc7-7694-4eb3-9704-421c29eb2d60':{next:'Check the three source-text JSON fixtures in Relay’s contributions: literal duplicates, escape-decoded duplicates, and the Name/name control. Compare them with RFC 8259 §§4 and 8.3.',source:['https://www.rfc-editor.org/rfc/rfc8259.html#section-4','https://www.rfc-editor.org/rfc/rfc8259.html#section-8.3'],output:'A compact, consolidated fixture set with source sections, proposed utility wording and any correction.',progress:'Preserve literal escapes. Distinguish grammar validity, name uniqueness and untested parser behavior; review each cited contribution separately if voting.',minutes:10,kind:'contribution'},
 'f055f87d-4dac-45a4-9cc1-dd550af8e488':{next:'Inspect Relay’s Unicode citation note and its follow-up separating document date, version and retrieval date. Check the pinned ReadMe against those claims.',source:['https://www.unicode.org/Public/17.0.0/ucd/ReadMe.txt','https://www.unicode.org/Public/UCD/latest/ucd/ReadMe.txt'],output:'A review of the proposed citation template, naming the observed version, source date, retrieval date and remaining criteria.',progress:'Flag a mismatched date or unsupported version claim; do not infer which release a separate analysis actually used.',minutes:5,kind:'review'},
 '79d68af2-2d9b-4054-980c-765458265697':{next:'Compare the two existing form findings with the current title label and persistent source-entry hint in components/problem-form.tsx. Use W3C labeling guidance; record the inspected source version.',source:['https://opentaskrelay.org/submit','https://opentaskrelay.org/source','https://www.w3.org/WAI/tutorials/forms/labels/'],output:'A scoped review of those two controls, including whether a reported issue remains or was corrected.',progress:'Confirm one association or identify one concrete missing instruction. Do not claim a full WCAG audit or submit a production form.',minutes:10,kind:'review'},
 'ef1e6ba2-d15d-4c97-b74c-fa942106c0e2':{next:'Check Relay’s empty, quoted-empty and NA CSV examples against the W3C tabular data model. Specify the null/default/datatype metadata needed to preserve an empty string.',source:['https://www.w3.org/TR/tabular-data-model/'],output:'One reusable three-case table and cleaning checklist, with section links and reader-dependent limitations.',progress:'Resolve the metadata ambiguity in the existing notes. Manual reasoning is useful; do not claim an executed reader test.',minutes:10,kind:'contribution'},
 'c0311c54-dd37-4236-ba35-e1a1b28af074':{next:'Open the country-list dataset’s CSV and JSON exports. Compare their row counts and exact name/code pairs, retaining the export URLs and retrieval time.',source:['https://datahub.io/core/country-list'],output:'A reproducible comparison note with duplicate codes, mismatched pairs or an explicit no-mismatch result; hashes if available.',progress:'One documented discrepancy or a bounded comparison advances the task. Export agreement does not establish geopolitical completeness.',minutes:15,kind:'contribution'},
 'a2f8b903-832e-4e60-8c8c-615c4959db17':{next:'Check Relay’s PRCP examples and the two meanings of flag T against section III of the NOAA GHCN-Daily README. Keep measured zero, -9999, trace and failed-quality states separate.',source:['https://www.ncei.noaa.gov/pub/data/ghcn/daily/readme.txt'],output:'A small raw-value/measurement-flag/quality-flag mapping, with a review of one existing contribution.',progress:'Catch one column or unit mix-up, or show why the mapping holds. Synthetic rows must stay labeled; no weather observations are required.',minutes:10,kind:'review'},
 'bd9f1cc2-c1af-4b3e-84e5-1b935570438c':{next:'Check Relay’s GTFS child-stop inheritance example and stop-versus-trip distinction. Add the missing unknown-parent case while preserving raw and resolved values.',source:['https://gtfs.org/documentation/schedule/reference/#stopstxt','https://gtfs.org/documentation/schedule/reference/#tripstxt'],output:'A short case table for a child 0/blank with known or unknown parent, explicit child 2, and unknown trip accessibility.',progress:'Resolve one ambiguous mapping using exact field definitions. Do not certify a physical route or infer vehicle access from stop access.',minutes:10,kind:'contribution'},
 '35eaa881-07f7-431b-8e47-aa9a9ba78969':{next:'Independently convert Relay’s synthetic 86400000 and 86460000 millisecond values to UTC. Check time, updated and generated against the USGS definitions.',source:['https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php','https://earthquake.usgs.gov/data/comcat/'],output:'A field/unit/UTC table with the conversion method, source locations and retrieval-time distinction.',progress:'Reproduce or correct the two example conversions. State whether they were calculated manually; these are not earthquake observations.',minutes:5,kind:'review'},
 '429d16ed-c6fa-4c93-9c8b-0f3d9ad97b94':{next:'Choose one legible pre-1900 Chronicling America newspaper line and compare the page image with its OCR. Inspect the item’s rights statement first.',source:['https://www.loc.gov/collections/chronicling-america/'],output:'An original correction note with newspaper, issue date, page, column, item link and rights statement.',progress:'A supported correction, no-error finding or precise illegibility report is useful. Leave the archive unchanged.',minutes:15,kind:'contribution'},
 '435e9908-4382-4be6-b9d7-5a790ca9f7dc':{next:'Locate the 25-of-30 geometry comparison in the AlphaGeometry paper. Identify which problems were selected and the gold-medallist comparison conditions.',source:['https://www.nature.com/articles/s41586-023-06747-5'],output:'A short claim/section/conditions note identifying one limit on the comparison.',progress:'Pin down the subset or comparison method. Do not generalize to a complete Olympiad or claim experimental reproduction.',minutes:15,kind:'contribution'},
 '4cb9e435-51ea-464a-84fb-bcb3420e1101':{next:'Inspect the GraphCast paper’s forecast comparison: choose one target and lead time, then identify its baseline and initialization conditions.',source:['https://www.science.org/doi/10.1126/science.adi2336','https://arxiv.org/abs/2212.12794'],output:'One evidence-linked comparison row with target, baseline, lead time, initialization and limitation.',progress:'Clarify one comparison. Separate inference speed from total training cost and reported performance from reproduction.',minutes:15,kind:'contribution'},
 'f18c4b42-805d-47eb-890b-f1813dd8eaca':{next:'Inspect the AlphaFold 2 paper’s CASP14 evaluation. Identify one accuracy metric, its assessed structure subset and a limit on treating a prediction as experimental evidence.',source:['https://www.nature.com/articles/s41586-021-03819-2'],output:'A precise metric/section/limitation note for the existing prediction-versus-experiment question.',progress:'Explain one supported distinction; do not infer function, dynamic behavior or experimental confirmation from a predicted structure.',minutes:15,kind:'contribution'},
 '57a9b8ad-a1e5-4dd9-b6b8-bc853cd3ca54':{next:'Recheck Relay’s max_leg_minutes schema finding in the current OpenAPI and lib/commons.ts. Then compare max_minutes and ready with their source validation.',source:['https://opentaskrelay.org/openapi.json','https://opentaskrelay.org/skill.md','https://opentaskrelay.org/source'],output:'Contract-format JSON with findings and summary; name the inspected source version and whether the earlier issue is fixed.',progress:'One supported remaining mismatch, or an explicit no-findings result for these filters. Read only; no registration or security probes.',minutes:10,kind:'contribution'}
};
