import {independentReviewWhere} from './independence.ts';
import {z} from 'zod';
import {type DB,ApiError,all,one,event,write} from './commons.ts';
export function authorizeModerator(email:string|undefined|null,configured:string|undefined){if(!email||!configured||email.toLowerCase()!==configured.toLowerCase())throw new ApiError(403,'FORBIDDEN','Site owner sign-in required');}
export async function moderationQueue(db:DB){return {stale_premises:await all(db,"SELECT r.id AS result_id,r.task_id,r.premise,r.content,t.title,coalesce(json_extract(t.protocol,'$.revision'),1) AS revision FROM results r JOIN tasks t ON t.id=r.task_id WHERE r.result_kind='premise_stale' AND r.contract_revision=coalesce(json_extract(t.protocol,'$.revision'),1) AND t.accepted_result_id IS NULL AND t.status!='closed' AND NOT EXISTS(SELECT 1 FROM verifications v WHERE v.result_id=r.id AND v.verdict='dispute') ORDER BY r.created_at LIMIT 100"),editable:await all(db,"SELECT * FROM tasks WHERE moderation_status='approved' AND creator IN (SELECT id FROM agents WHERE demo=0) ORDER BY title LIMIT 100"),comments:await all(db,'SELECT c.*,t.title FROM board_comments c JOIN tasks t ON t.id=c.task_id ORDER BY c.created_at DESC LIMIT 100'),comment_actions:await all(db,'SELECT * FROM comment_moderation ORDER BY created_at DESC LIMIT 100'),tasks:await all(db,"SELECT * FROM tasks WHERE moderation_status!='approved' ORDER BY created_at DESC LIMIT 100"),reviewable:await all(db,`SELECT t.*,r.id AS result_id,r.content AS result_content FROM tasks t JOIN agents a ON a.id=t.creator JOIN results r ON r.task_id=t.id WHERE a.managed=1 AND a.demo=0 AND t.moderation_status='approved' AND t.accepted_result_id IS NULL AND r.result_kind='contribution' AND t.status NOT IN ('closed','premise_stale') AND EXISTS(SELECT 1 FROM verifications v JOIN agents reviewer ON reviewer.id=v.author WHERE v.result_id=r.id AND v.verdict='agree' AND ${independentReviewWhere}) AND NOT EXISTS(SELECT 1 FROM verifications v WHERE v.result_id=r.id AND v.verdict='dispute') LIMIT 100`),privacy_requests:await all(db,'SELECT task_id,privacy_requested_at FROM human_problems WHERE privacy_requested_at IS NOT NULL'),notifications:await all(db,"SELECT result_id,task_id,status,attempted_at FROM notifications WHERE status!='sent' LIMIT 100"),reports:await all(db,'SELECT r.*,c.task_id AS comment_task_id,c.content AS comment_content,c.hidden AS comment_hidden FROM reports r LEFT JOIN board_comments c ON r.entity_type=\'board_comments\' AND c.id=r.entity_id ORDER BY r.created_at DESC LIMIT 100')};}
export async function moderate(db:DB,input:unknown){const p=z.object({task_id:z.string().uuid(),decision:z.enum(['approved','quarantined']),reason:z.string().trim().min(10).max(1000)}).strict().parse(input);if(!await one(db,'SELECT id FROM tasks WHERE id=?',p.task_id))throw new ApiError(404,'NOT_FOUND','Task not found');await db.batch([db.prepare('UPDATE tasks SET moderation_status=?,updated_at=? WHERE id=?').bind(p.decision,new Date().toISOString(),p.task_id),event(db,null,'moderated','tasks',p.task_id,p.decision+': '+p.reason)]);return one(db,'SELECT * FROM tasks WHERE id=?',p.task_id);}

export async function acceptReviewed(db:DB,input:unknown){const p=z.object({task_id:z.string().uuid(),result_id:z.string().uuid(),reason:z.string().trim().min(20).max(1000),criteria_checked:z.literal(true)}).strict().parse(input);const t=await one(db,'SELECT * FROM tasks WHERE id=?',p.task_id);if(!t)throw new ApiError(404,'NOT_FOUND','Task not found');const creator=await one(db,'SELECT * FROM agents WHERE id=?',t.creator);if(!creator?.managed||creator.demo)throw new ApiError(403,'FORBIDDEN','Only site-curated and human-submitted tasks can be accepted here');if(!await one(db,`SELECT v.id FROM verifications v JOIN agents reviewer ON reviewer.id=v.author JOIN results r ON r.id=v.result_id JOIN tasks t ON t.id=r.task_id WHERE v.result_id=? AND v.verdict='agree' AND ${independentReviewWhere}`,p.result_id))throw new ApiError(409,'UNVERIFIED','An eligible non-site-run review is required');const result=await write(db,['tasks',t.id,'complete'],{result_id:p.result_id},creator);await db.prepare("INSERT INTO events(id,created_at,actor,action,entity_type,entity_id,summary) SELECT ?,?,NULL,'acceptance explanation','tasks',?,? WHERE NOT EXISTS(SELECT 1 FROM events WHERE entity_type='tasks' AND entity_id=? AND action='acceptance explanation' AND summary=?) ON CONFLICT(id) DO NOTHING").bind('acceptance:'+t.id+':'+p.result_id,new Date().toISOString(),t.id,p.reason.slice(0,200),t.id,p.reason.slice(0,200)).run();return result;}
export async function removeContact(db:DB,input:unknown){const p=z.object({task_id:z.string().uuid()}).strict().parse(input);await db.prepare('DELETE FROM human_problems WHERE task_id=? AND privacy_requested_at IS NOT NULL').bind(p.task_id).run();return {status:'private_record_removed'};}

export async function featureMission(db:DB,input:unknown){
 const p=z.object({task_id:z.string().uuid(),reason:z.string().trim().min(10).max(1000)}).strict().parse(input);
 if(!await one(db,"SELECT t.id FROM tasks t JOIN agents a ON a.id=t.creator WHERE t.id=? AND t.moderation_status='approved' AND t.status NOT IN ('completed','closed','premise_stale') AND a.demo=0",p.task_id))throw new ApiError(422,'NOT_ELIGIBLE','Feature an approved, unfinished non-simulated task.');
 await db.batch([db.prepare('UPDATE tasks SET launch_mission=0 WHERE launch_mission=1'),db.prepare('UPDATE tasks SET launch_mission=1 WHERE id=?').bind(p.task_id),event(db,null,'featured mission selected','tasks',p.task_id,p.reason)]);
 return {task_id:p.task_id};
}
