import type {categoryKeys} from './categories.ts';

export type ExpansionBrief={id:string;category:typeof categoryKeys[number];title:string;benefit:string;scope:string;sources:[string,string][];first:string;output:string;criteria:string[];minutes?:number;code?:boolean};

// Additive owner-requested briefs. Source discovery: 2026-09-09.
// These are research assignments, not completed findings or claims of defects.
export const expansionBriefs:ExpansionBrief[]=[
 {id:'140fe88a-eb39-4cbc-8bfd-b50790e3bc19',category:'environment',title:'Reconcile Portland sorting advice for food-soiled packaging',
  benefit:'Apartment residents and community kitchens need to avoid transferring household compost rules to business or shared bins.',
  scope:'Compare Portland’s current recycling, compost and garbage pages for pizza boxes, paper towels, coffee cups, takeout containers and compostable utensils. Separate household, multifamily and business collection. Include the June 2026 recycling update without assuming every building has the same service.',
  sources:[['https://www.portland.gov/bps/garbage-recycling/compost','Home versus business rules and multifamily qualifications'],['https://www.portland.gov/bps/garbage-recycling/recycling','Current recycling rules; follow the linked garbage guidance'],['https://www.portland.gov/bps/garbage-recycling/news/2026/6/15/yes-you-can-recycle-pizza-boxes-and-other-recycling-updates','Dated recycling changes']],
  first:'Check pizza boxes and paper towels across the three collection settings. Return two evidence-linked rows and any building-specific question the city says must be resolved.',
  output:'A five-item sorting matrix, dated change notes and an original plain-text sign draft for a community kitchen.',
  criteria:['Keep collection setting and clean versus food-soiled condition explicit.','Account for conflicting or superseded instructions using publication dates; never invent local acceptance.','The sign must say which service it describes and retain unknown building-specific rules.'],minutes:10},
 {id:'73d449cd-ae4c-42c0-8961-22ec4cab8d76',category:'environment',title:'Build a paint-reuse and drop-off guide for Oregon community cleanups',
  benefit:'Volunteer cleanup organizers need to separate reusable paint, accepted coatings and materials that need another disposal route.',
  scope:'Compare Oregon DEQ and PaintCare for latex paint, oil-based paint, stain, aerosol coatings and leaking or unlabeled containers. Distinguish purchase fees, drop-off conditions and PaintShare reuse; do not assume a listed site has capacity or accepts every material.',
  sources:[['https://www.oregon.gov/deq/mm/pages/paint.aspx','State program and linked stewardship guidance'],['https://www.paintcare.org/states/oregon/','Oregon program, reuse and collection routes'],['https://www.paintcare.org/products/','Accepted and excluded products and container requirements']],
  first:'Compare the published rules for labeled latex paint and aerosol coatings. Cite the exact acceptance conditions and the official alternate-route starting point for exclusions.',
  output:'Five material records, a reuse-versus-disposal decision note and a list of capacity questions for organizers to confirm separately.',
  criteria:['Do not equate no published drop-off charge with no purchase fee.','Do not give mixing, decanting, transport or hazardous-handling instructions.','Separate program rules from individual-site capacity and do not arrange a collection.']},
 {id:'b2d293f1-27be-4aa4-b408-fee3efa4b1d0',category:'environment',title:'Find seasonal gaps in a western Montana native-pollinator plant list',
  benefit:'Community garden volunteers need a source-grounded way to discuss flowering-season coverage before buying seed.',
  scope:'Use NRCS and Montana State University guidance to select eight native flowering species relevant to western Montana. Compare published bloom periods, moisture needs and regional qualifications. Identify apparent gaps in early-, middle- and late-season coverage without prescribing a planting or promising pollinator outcomes.',
  sources:[['https://www.nrcs.usda.gov/resources/guides-and-instructions/pollinators-montana-resources','Official plant-material references and pollinator resources'],['https://extension-store.montana.edu/montguides/native-plants-for-montanas-home-gardens','Extension species guidance and local-site qualifications']],
  first:'Document two species with their scientific names and published flowering windows. Record which western Montana site conditions remain unresolved.',
  output:'An eight-species seasonal-coverage table with source locations, regional limits and questions for a local garden planner.',
  criteria:['Use scientific names and distinguish native status from commercial cultivar availability.','Keep bloom dates as published ranges, not guarantees for a particular garden.','Do not recommend seed purchases, collect wild plants or infer a plant’s suitability from one trait.']},
 {id:'7db474e9-2bd6-4a6a-9a0e-60a650268326',category:'environment',title:'Explain assessment gaps in three Lower Cuyahoga waterway records',
  benefit:'Watershed volunteers need to distinguish an assessed impairment from water that has not been assessed for the same use.',
  scope:'In EPA How’s My Waterway, select the first three assessment units alphabetically in the Lower Cuyahoga watershed. Pin their identifiers and compare assessment cycle, designated use, assessed status and listed causes. This is a public-record interpretation task, not a swimming, fishing or drinking-water advisory.',
  sources:[['https://www.epa.gov/waterdata/hows-my-waterway','Tool coverage, update limitations and official application link'],['https://www.epa.gov/waterdata/attains','Assessment definitions and public data-service links']],
  first:'Record the exact watershed and three-unit sample, then trace one unit’s assessment cycle and one use-specific status back to its source record.',
  output:'Three assessment-unit records and a short explanation of what missing assessments prevent readers from concluding.',
  criteria:['Use assessment-unit identifiers; do not merge similarly named river segments.','Separate uses, assessment cycles and causes; missing assessment never means clean or safe.','Retain EPA’s data-lag qualifications and provide exact record links or a reproducible query.']},
 {id:'c5f6086f-3a6c-4836-9ec6-81d8fedfebc4',category:'environment',title:'Reconcile Florida invasive-plant labels without confusing them with legal bans',
  benefit:'Volunteer habitat-restoration groups need to understand why different authoritative plant lists use different labels.',
  scope:'Compare the first five species alphabetically in the current FISC Category I list with their linked UF/IFAS assessments. Record scientific names, synonyms, regional qualifications and the meaning of each label. Use UF/IFAS’s guide to distinguish advisory classifications from regulatory lists.',
  sources:[['https://www.floridainvasives.org/plant-list/2023-invasive-plant-species/','Species table, categories and assessment links; verify edition'],['https://ask.ifas.ufl.edu/publication/AG436','Explanation of Florida’s different non-native plant lists']],
  first:'Pin the list edition and sample. Reconcile one species’ name and regional assessment, preserving any mismatch rather than choosing a preferred label.',
  output:'A five-species crosswalk and an original legend explaining which conclusions each list does and does not support.',
  criteria:['Do not treat FISC or UF/IFAS assessment status as proof of a legal prohibition.','Retain synonyms and regional qualifiers; identify unresolved taxonomic matches.','No removal, pesticide, handling or introduction instructions, and no sensitive species coordinates.']},

 {id:'6b2dd52d-6f25-4829-9e01-816ef92cd851',category:'public-safety',title:'Check smoke-alarm assistance routes for three Red Cross regions',
  benefit:'Housing volunteers need a reliable referral sheet for residents who cannot readily obtain or install alarms.',
  scope:'Follow the Red Cross Sound the Alarm directory for the regions serving Detroit, Baltimore and Dallas. Compare public request routes, stated service areas, renter requirements and any published accommodations for people who are deaf or hard of hearing. A request route is not a guaranteed appointment.',
  sources:[['https://www.redcross.org/sound-the-alarm.html','National program and local smoke-alarm request links']],
  first:'Follow the Detroit-region link and record its request channel, stated coverage and any accommodation information. Leave undocumented eligibility or equipment details unknown.',
  output:'Three region-specific referral records with dated source links, published limits and questions a resident would still need answered.',
  criteria:['Use the actual regional program page, not a national promise applied locally.','Distinguish standard smoke alarms from documented specialized alerting equipment.','Do not submit requests, disclose household information or provide installation instructions.'],minutes:10},
 {id:'3fd589a1-b866-4ccc-87b7-8c688804281c',category:'public-safety',title:'Compare California and Oregon wildfire evacuation terminology',
  benefit:'People traveling or relocating across state lines need to recognize that official evacuation labels are not interchangeable.',
  scope:'Locate Oregon’s current three-level evacuation explanation and CAL FIRE’s current map legend. Create a side-by-side terminology reference with official action wording, issuing-authority qualifications and links to local alerts. Do not assign equivalence between levels or describe any location’s current risk.',
  sources:[['https://wildfire.oregon.gov/','Follow Evacuations: Be Ready. Be Set. Go Now!'],['https://www.fire.ca.gov/','Follow incident-map legend and evacuation terminology']],
  first:'Locate and date the two exact guidance pages. Compare one Oregon level with California’s warning label and explicitly identify why a one-to-one mapping may mislead.',
  output:'A source-linked terminology table and a short original travel-reference note directing people to the responsible local authority.',
  criteria:['Preserve differences in labels, authority and official actions instead of inventing a unified scale.','No current incident assessment, route recommendation or instruction to delay evacuation.','Keep this reference separate from live alerts and identify guidance that could not be retrieved.']},
 {id:'0f40a842-f014-4c85-9b2b-2ecfb1e0009c',category:'public-safety',title:'Recheck outdated life-jacket loaner listings against Washington’s current map',
  benefit:'Families and youth-group organizers need to know which published loaner listings still have current supporting information.',
  scope:'Select the first five stations alphabetically in the June 2013 statewide list hosted by Snohomish County. Match them to the current Washington State Parks map and public operator pages. Compare names, public locations, season and stated borrowing process; do not infer inventory or mark an absent listing closed.',
  sources:[['https://snohomishcountywa.gov/DocumentCenter/View/831/Whashington-State-Life-Jacket-Loaner-Stations','Historical June 2013 station list; not current availability'],['https://parks.wa.gov/about/rules-and-safety/boater-education-safety/life-jacket-loaner-program','Current official program and map']],
  first:'Pin the five-station sample and check one historical entry against the current map. Record a supported match, possible match or unresolved result with both source dates.',
  output:'A five-record historical-to-current crosswalk with current official links and an explicit inventory/fit/availability limitation.',
  criteria:['Keep historical and current evidence in separate fields.','A missing map entry is unresolved, not proof that a station closed.','Do not promise stock, recommend a fit, or present this as permission to enter the water.']},
 {id:'d104e788-f61f-45ff-a21e-40bbd9b3c89d',category:'public-safety',title:'Make Florida beach-warning references understandable without color alone',
  benefit:'Visitors reading printed or low-color material need the official warning meanings expressed in words as well as flag colors.',
  scope:'Compare the Florida DEP beach-warning program with Volusia County’s published flag explanations. Draft a plain-text reference covering every flag combination in those sources and explain the limits of a static handout. Check whether county-specific qualifications change any wording.',
  sources:[['https://floridadep.gov/','Locate the Beach Warning Flag Program and its official sign'],['https://www.volusia.org/','Locate Beach Safety: Beach warning flags']],
  first:'Find the exact two guidance pages and compare single-red with double-red wording. Draft two text-first labels with precise citations and no current-condition claims.',
  output:'An original color-independent warning reference, source comparison and list of local qualifications or missing explanations.',
  criteria:['Preserve distinct meanings and flag combinations; never equate a low-hazard flag with safe water.','Do not infer current flags, lifeguard coverage or permission to swim.','Clearly label the handout as a static reference and point to official on-site/current instructions.']},
 {id:'3cdcdd06-9b66-49a2-919d-33841e513631',category:'public-safety',title:'Separate pet-evacuation preparation from promised shelter availability in Multnomah County',
  benefit:'Pet-owning households need to understand what local preparedness pages actually promise before relying on emergency boarding.',
  scope:'Compare Multnomah County’s 2020 preparedness release with current Animal Services disaster guidance. Extract references to household pets, livestock, transport and emergency boarding. Identify changed or conditional wording without constructing a live shelter directory.',
  sources:[['https://multco.us/news/release-prepare-your-pets-emergencies','Dated 2020 county release'],['https://www.multcopets.org/disaster-preparedness','Current county animal-services guidance and capacity qualifications']],
  first:'Trace the boarding-capacity statement in both sources and return one dated comparison, distinguishing preparation advice from an active service offer.',
  output:'A four-topic comparison and an original planning-question sheet with current official follow-up links.',
  criteria:['Keep household pets, service animals and livestock distinct where the source does.','Do not list an organization as an open shelter merely because it participates in disaster response.','No transport, boarding requests, private animal-owner data or unsupported animal-care advice.'],minutes:10},

 {id:'bef4310a-832b-467c-b87b-b9cfa5bcd6e7',category:'accessibility',title:'Compare offline enrollment paths for talking-book and braille services',
  benefit:'People with print disabilities and library volunteers need a starting-point guide that does not require a smartphone or online account.',
  scope:'Compare the national NLS application with its network libraries serving Montana, North Dakota and Kentucky. Record mail/phone starting points, application formats, published certification requirements and equipment information. Do not assess an individual’s eligibility.',
  sources:[['https://www.loc.gov/nls/how-to-enroll/apply-for-nls-services/','Eligibility guidance and network-library directory'],['https://www.loc.gov/nls/how-to-enroll/apply-for-nls-services/application-in-english-spanish-and-for-institutions/','National application formats']],
  first:'Follow the Montana network-library link and compare its offline application route with the national instructions. Return one sourced row and unresolved format questions.',
  output:'Three state-library enrollment rows, an accessible-format checklist and a short no-account starting guide.',
  criteria:['Distinguish NLS enrollment, equipment requests and optional online-download registration.','Use exact local-library instructions; do not invent accommodations or eligibility decisions.','Do not collect diagnoses, certification documents, names or applications.']},
 {id:'2ac665d5-4952-4ad4-9868-3d253cbdc3e3',category:'accessibility',title:'Compare everyday sensory supports with scheduled Smithsonian programs',
  benefit:'Families and visitors with sensory sensitivities need to distinguish an everyday museum feature from a limited registration-based event.',
  scope:'Compare the National Portrait Gallery, Smithsonian American Art Museum and National Museum of American History using their official visitor pages and Smithsonian access guidance. Extract quiet-space information, pre-visit resources, equipment policies and Morning at the Museum requirements without assuming an event is currently bookable.',
  sources:[['https://www.si.edu/visit/accessibility','System-wide visitor access and equipment policies; follow museum pages'],['https://access.si.edu/program/morning-museum','Program scope and dated event/registration information']],
  first:'Complete the National Portrait Gallery row for everyday supports versus scheduled programming, recording dates and any required registration.',
  output:'A three-museum comparison and a concise visit-planning question list for details the published pages do not settle.',
  criteria:['Keep recurring visitor information separate from dated event listings.','Missing sensory-bag or quiet-room information does not prove availability or absence.','Do not diagnose sensory needs, certify suitability, register or contact staff.']},
 {id:'fe7406f1-f6a0-4100-ac1b-ceb9aa124823',category:'accessibility',title:'Compare published boarding-access details at three Montana Amtrak stations',
  benefit:'Travelers using mobility devices need station-specific questions answered before treating a general accessibility statement as a complete journey plan.',
  scope:'Compare Havre, Shelby and Whitefish station pages with Amtrak’s boarding and reservation guidance. Extract platform access, waiting-room/restroom information, staffing and how assistance is requested. This is a desk reference, not a verified itinerary.',
  sources:[['https://www.amtrak.com/station-accessibility','Station directory, access definitions and assistance guidance'],['https://www.amtrak.com/making-reservations-for-customers-with-a-disability','Published reservation and accommodation channels']],
  first:'Locate Havre’s official station page and record three access fields with exact source sections. Identify which assistance details are station-specific and which remain general.',
  output:'Three comparable station records with public source links, retrieval dates and unresolved journey-planning questions.',
  criteria:['Separate station, platform, train and connecting-service access.','Do not infer working lifts, compatible equipment or current staffing from a general policy.','No bookings, purchases, calls or individual disability data.']},
 {id:'bdab2aa7-4a31-417d-9e6d-c863e0d22d75',category:'accessibility',title:'Create a text-first companion to one public USGS streamflow graph',
  benefit:'Screen-reader users and low-bandwidth readers need a faithful way to understand the information conveyed by a community water-data graph.',
  scope:'Locate the USGS Gallatin River at Logan, Montana monitoring record and pin a seven-day historical window, August 1–7, 2026. Use the underlying daily discharge values to draft a text summary and plain-text table. Preserve units, missing values and provisional flags; do not interpret flood risk.',
  sources:[['https://waterdata.usgs.gov/','Official monitoring-location search, graphs and tabular downloads'],['https://www.usgs.gov/water-data-for-the-nation','Water Data for the Nation context and documentation']],
  first:'Verify the station identifier and retrieve the first two dates. Draft a table header and two rows that remain intelligible without color, images or visual position.',
  output:'A seven-day text table, short graph-equivalent description and fidelity checklist linking each statement to underlying data.',
  criteria:['Use the same station, parameter, units and dates throughout.','Describe only supported patterns; preserve gaps instead of interpolating.','Do not claim screen-reader testing was performed or provide an emergency forecast.']},
 {id:'423310b6-9878-4e21-9b22-e478fcc43e96',category:'accessibility',title:'Check whether three state voter guides explain accessible voting options clearly',
  benefit:'Voters with disabilities and nonpartisan helpers need official information that separates available formats from the steps for requesting assistance.',
  scope:'Follow the EAC’s state-election links for Montana, North Dakota and Kentucky. Compare their public accessibility guides for in-person equipment information, accessible absentee information, alternative document formats and official assistance contacts. Do not infer eligibility, deadlines or availability where undocumented.',
  sources:[['https://www.eac.gov/voting-accessibility','Nonpartisan accessibility resources and official election-office links']],
  first:'Locate Montana’s official accessibility guide and document two supported options, their scope and a missing or ambiguous instruction.',
  output:'A dated three-state information-gap table with direct official links and a neutral plain-language summary.',
  criteria:['Keep state and local procedures distinct and pin any election-specific dates.','No political advocacy, voter targeting, registration, ballot submission or private voter data.','Do not certify legal compliance or independently advise how a person should vote.']},

 {id:'153ec2c5-bd5d-4340-a3cb-e2630d522273',category:'science',title:'Check which snowpack baselines support a Montana basin comparison',
  benefit:'Community water researchers need to know whether snow-water-equivalent percentages use comparable dates and reference periods.',
  scope:'Locate NRCS’s public snowpack reports for the Gallatin, Madison and Jefferson basins on April 1, 2026. Compare station coverage, snow-water-equivalent units, median/reference periods and missing-data notes. Do not treat basin percentages as a water-supply forecast.',
  sources:[['https://www.nrcs.usda.gov/','Follow National Water and Climate Center snowpack reports and Montana water-supply products']],
  first:'Pin the exact Gallatin report and its reference period. Return the source row, station-coverage information or unknown, and the definition of the reported percentage.',
  output:'Three basin evidence rows, a comparability checklist and a short account of which differences cannot be interpreted from these reports alone.',
  criteria:['Keep date, metric and reference period explicit; snow depth is not snow water equivalent.','Do not silently substitute averages for medians or station values for basin values.','No runoff prediction, drought declaration or gap filling.']},
 {id:'d751bf9b-622a-4053-b375-93a8241054ec',category:'science',title:'Preserve uncertainty when deriving flowering dates from citizen observations',
  benefit:'Community ecology groups need a defensible rule for turning repeated observations into a flowering-date record.',
  scope:'Use USA-NPN documentation and one small public eastern-redbud observation series from a U.S. site. Pin the site/plant record without publishing private observer details. Compare yes, no, uncertain and missing observations; show the interval supported for first flowering instead of inventing an exact start date.',
  sources:[['https://www.usanpn.org/node/223','Nature’s Notebook documentation and observation meanings'],['https://www.usanpn.org/data/quality','Data-quality and uncertainty guidance']],
  first:'Locate the relevant phenophase definition and document an original rule for a no-to-yes transition with a gap. If a public observation series is accessible, apply it to one transition; otherwise identify that specific data-access step.',
  output:'A source-pinned observation excerpt, transparent interval derivation and an uncertainty note suitable for a community dataset.',
  criteria:['Never convert missing or uncertain observations to no.','Separate observed flowering from model-derived spring indices.','No new observations, private observer profiles, rare-species locations or causal climate claim from one series.']},
 {id:'23dad60b-7d75-4e0a-84d9-2ec57deb5fb4',category:'science',title:'Compare relative sea-level evidence at three U.S. tide gauges',
  benefit:'Coastal community researchers need trend statements that retain record length, uncertainty and local land-motion qualifications.',
  scope:'Locate NOAA trend records for Grand Isle, Galveston Pier 21 and The Battery. Compare published trend units, confidence intervals, record windows and relative-versus-global meaning. Reproduce only explicitly documented conversions; do not make a neighborhood flood forecast.',
  sources:[['https://www.noaa.gov/sea-level-trends','NOAA explanation and station-data links'],['https://tidesandcurrents.noaa.gov/sltrends/slrmap.html','Station trend records and relative sea-level context']],
  first:'Verify Grand Isle’s station identifier, trend window and confidence interval. Return one citation-ready row and the limitation on interpreting it as global sea-level change.',
  output:'A three-station comparison with exact source versions and an original explanation of why unequal record windows matter.',
  criteria:['Use the published station identities and units, retaining intervals and record dates.','Do not rank future local danger from historical linear trends.','Distinguish relative sea level from ocean-only change and label every derived calculation.']},
 {id:'a5ef45f8-381b-4d78-a0f2-7e61e2460c2a',category:'science',title:'Make NEON water-quality flags usable in a small community research extract',
  benefit:'Volunteer freshwater researchers need to avoid treating flagged instrument readings as equally reliable measurements.',
  scope:'Use NEON’s aquatic instrument tutorial and its linked public sample to select a 24-hour dissolved-oxygen extract. Pin the product, site, time zone, averaging interval and release. Compare automated and manual quality flags without running downloaded tutorial code.',
  sources:[['https://www.neonscience.org/resources/learning-hub/tutorials/explore-neon-ais-data','Public sample, product documentation and quality-flag definitions']],
  first:'Locate the sample and its flag dictionary. Return two observed flag fields with their meanings and a source-grounded rule for keeping them attached to values.',
  output:'A small annotated data extract, flag dictionary and reproducible inclusion/exclusion note with unresolved flags retained.',
  criteria:['Do not equate an unflagged value with guaranteed accuracy or silently discard flagged rows.','Keep instantaneous and time-averaged products separate.','No tutorial-code execution, water-safety judgment or fabricated sample if download access fails.']},
 {id:'4fe2c198-b170-4ee2-bd97-22a79986d93e',category:'science',title:'Separate measured surface moisture from modeled root-zone moisture in SMAP products',
  benefit:'Drought researchers and community agricultural educators need to know which soil-moisture claims come from measurements and which depend on models.',
  scope:'Compare one current NASA SMAP surface-moisture product and one Level 4 root-zone product using their official product guides. Pin versions and extract depth, spatial resolution, temporal aggregation, units and quality limitations. Build an interpretation guide, not an irrigation recommendation.',
  sources:[['https://smap.jpl.nasa.gov/data/','NASA product list, measurement scope and linked product guides']],
  first:'Locate both product guides and complete depth and measured-versus-modeled fields with page or section references.',
  output:'A two-product metadata matrix and four original example statements labeled supported, qualified or unsupported by the product definitions.',
  criteria:['Keep direct sensing, model assimilation and derived estimates distinct.','Do not treat a grid cell as a measurement of a particular field or property.','No farm-management recommendation, causal crop-yield claim or execution of downloaded tools.']},

 {id:'a967c18f-d5d5-4874-805a-b06c02747b62',category:'education',title:'Create an original unit-price lesson for adult grocery shoppers',
  benefit:'Adult numeracy tutors need practice that teaches useful comparisons without relying on current prices or paid learning platforms.',
  scope:'Write eight original practice cases using clearly fictional shelf labels, covering equal units, different package sizes, mixed units and a misleading multi-buy offer. Include worked calculations and a note that lowest unit price is not always the best personal purchase.',
  sources:[['https://openstax.org/books/prealgebra-2e/pages/5-6-ratios-and-rate','Unit-rate concepts and worked-method reference']],
  first:'Draft two fictional same-unit comparisons and their worked answers, explicitly labeling all prices as practice data.',
  output:'A printable learner sheet, separate worked-answer key and tutor notes explaining unit and rounding mistakes.',
  criteria:['Create original questions rather than copying the textbook.','Verify arithmetic, units and rounding; do not use invented prices as real market facts.','Use respectful adult language and require no images, accounts or purchases.'],minutes:10},
 {id:'eebf868f-8826-4d35-97b3-3e62af574b3b',category:'education',title:'Build a source-evaluation activity around two public-domain historical images',
  benefit:'Middle-school teachers need a reusable lesson that distinguishes observation from inference without partisan examples.',
  scope:'Choose two Library of Congress images of everyday U.S. community life with clear rights statements. Create original observe/reflect/question prompts, a provenance comparison and teacher notes showing which questions the images alone cannot answer. Do not reproduce restricted images.',
  sources:[['https://www.loc.gov/programs/teachers/getting-started-with-primary-sources/guides/','Primary-source analysis guidance and source-type prompts']],
  first:'Select and cite one rights-cleared item. Draft three observation prompts and two inference questions, with teacher notes explaining the difference.',
  output:'A two-source lesson with item links, descriptive alternatives, six prompts, answer guidance and explicit uncertainty notes.',
  criteria:['Record creator, date, collection identifier and rights statement for each item.','Avoid treating a photograph’s caption as independent confirmation of every claim.','Use original prompts and do not present speculation as the answer key.']},
 {id:'d46dcc0b-5d4a-48b0-98ed-81f712a2393d',category:'education',title:'Turn early-reading evidence into short volunteer tutor practice cards',
  benefit:'Volunteer reading tutors need brief, usable activities with a clear connection to evidence and no claims of diagnosing a child.',
  scope:'Use the IES foundational-reading practice guide to create four original 10-minute activity cards for beginning readers: sound awareness, letter-sound connections, decoding and connected-text reading. Pin which recommendation supports each card and preserve its stated evidence level.',
  sources:[['https://ies.ed.gov/ncee/wwc/PracticeGuide/21','Foundational reading recommendations, evidence ratings and linked implementation material']],
  first:'Read one recommendation and draft one activity card with original examples, a tutor script and a note on what the activity does not establish.',
  output:'Four printable cards, a source/evidence crosswalk and a short note for adapting instruction with the learner’s educator.',
  criteria:['Do not claim all recommendations have identical evidence strength.','No diagnosis, reading-level certification or promised learning gains.','Keep examples original, instructions age-respectful and the cards usable without an app.'],minutes:10},
 {id:'c9070276-e708-4826-9a8c-64887477420b',category:'education',title:'Compare adult high-school-equivalency learning options in three Montana communities',
  benefit:'Adults returning to education need to separate free instruction from test fees, transcript services and enrollment steps.',
  scope:'Compare public adult-education pages serving Billings, Helena and Butte through Montana OPI’s directory. Record instruction formats, published class costs, testing versus preparation, age conditions and no-account contact options. Do not enroll or promise admission.',
  sources:[['https://opi.mt.gov/Educators/Teaching-Learning/High-School-Equivalency-GED-and-HiSET-and-Adult-Community-Education-ACE','State program directory and testing/credential distinctions'],['https://adulteducation.billingsschools.org/adult-education-home/adult-education-about','Billings program description'],['https://adultlearningcenter.helenaschools.org/','Helena program and testing information']],
  first:'Complete Billings’s row for preparation, class cost and published eligibility, keeping any test fee in a separate field.',
  output:'Three program comparison rows, direct enrollment-information links and unresolved questions for a prospective learner.',
  criteria:['Free classes do not imply free testing, transport, materials or transcripts.','Use current provider pages and distinguish ongoing services from dated sessions.','No applications, personal education records or eligibility decisions.'],minutes:10},
 {id:'b7b2cbd7-627b-4d59-9968-4979b5597b58',category:'education',title:'Create an offline watershed lesson that distinguishes runoff from groundwater',
  benefit:'Community educators need a short water-literacy activity that works without a lab, internet connection or risky fieldwork.',
  scope:'Use USGS water-education resources to create an original classroom scenario with rain, a stream, soil and groundwater. Include six reasoning questions, a plain-text description instead of a required picture, and a worked answer guide that preserves uncertainty about a real watershed.',
  sources:[['https://www.usgs.gov/water-science-school/teachers-resources-water-education','USGS teacher resources and linked water-cycle explanations'],['https://www.usgs.gov/educational-resources/water-resources-education','Water-data and classroom resource context']],
  first:'Draft a 150-word original watershed scenario and two questions distinguishing surface runoff from infiltration, with source-grounded answer notes.',
  output:'A text-only learner page, six questions, separate answer guide and a short glossary with official source links.',
  criteria:['Do not imply all rainfall becomes runoff or that groundwater always moves directly to the nearest stream.','Label invented numbers as teaching examples and check any arithmetic.','No water sampling, drinking-water advice, experiments or unsupported local flood claims.'],minutes:10},

 {id:'a8415328-cfe7-4ee5-ab5c-708f49b0945a',category:'civic-public-information',title:'Compare federal public-record request fees without promising a waiver',
  benefit:'Community researchers need to distinguish filing a request from potential search, review and copying costs.',
  scope:'Compare current public FOIA instructions for Interior, Agriculture and HUD with FOIA.gov. Record fee categories, published waiver criteria, fee-estimate language and the official request route. Create a research-reference table, not a request or an eligibility determination.',
  sources:[['https://www.foia.gov/faq.html','General fee and waiver explanations and agency links'],['https://www.foia.gov/how-to.html','Request routing and scope'],['https://www.doi.gov/foia/fees-waivers','Interior’s agency-specific fee guidance']],
  first:'Complete Interior’s fee and waiver fields and identify which statements are general FOIA guidance versus agency-specific instructions.',
  output:'A three-agency fee/process matrix with exact source dates and a plain-language list of questions to settle before requesting records.',
  criteria:['No initial filing fee does not mean processing is always free.','Distinguish fee waiver, fee category and expedited processing; do not promise a decision or response time.','No actual requests, identity documents, contact or legal advice.']},
 {id:'d7ade950-a8be-44a2-a264-cee65f26c886',category:'civic-public-information',title:'Trace public-comment deadlines from rule notices to their official dockets',
  benefit:'Residents and public-interest researchers need to avoid relying on a stale deadline when a rule’s comment period has changed.',
  scope:'Select the two most recently published U.S. Department of Transportation proposed rules on FederalRegister.gov as of September 9, 2026. Pin document and docket identifiers. Compare original deadline wording with later extension/reopening notices and the linked docket’s public metadata; do not write or submit comments.',
  sources:[['https://www.federalregister.gov/reader-aids/using-federalregister-gov/the-public-commenting-process','Official commenting instructions and document search'],['https://www.regulations.gov/','Official docket metadata; read only']],
  first:'Pin the sample and trace one rule’s document ID to its docket. Record the original deadline and whether a linked extension was found, with search scope and timestamp.',
  output:'Two document-to-docket timelines with deadline provenance, uncertainty and direct official confirmation links.',
  criteria:['Distinguish a proposed rule, final rule, notice and extension; retain time-zone wording when published.','No extension found is a bounded search result, not proof that none exists.','Provide neutral procedural information only; no policy advocacy, submissions or accounts.']},
 {id:'2778cc53-9525-41c9-8add-68bc34dd3714',category:'civic-public-information',title:'Connect Missoula school-board agenda items to recorded decisions',
  benefit:'Families need a traceable way to see whether an agenda proposal was adopted, changed, deferred or merely discussed.',
  scope:'Use Missoula County Public Schools’ official Board Docs portal. Select the three most recent regular meetings with approved minutes published on or before September 9, 2026. Track one facilities or instructional-resource item from each agenda into the approved minutes; exclude student/personnel cases.',
  sources:[['https://www.mcpsmt.org/','Official Board of Trustees navigation and Board Docs portal for agendas/minutes']],
  first:'Identify the three eligible meetings, then trace one public facilities item from agenda title to its recorded disposition and minutes page.',
  output:'A three-item decision trail with meeting dates, agenda identifiers, minutes approval status and exact references.',
  criteria:['An agenda item alone is not evidence that a decision passed.','Use approved minutes where available; label drafts and exclude closed-session or personal matters.','Do not infer motives, collect student information or contact board members.']},
 {id:'ff1bbcf5-770e-4b66-a7dc-c4d77ced7aec',category:'civic-public-information',title:'Make Bozeman’s adopted budget fund totals understandable',
  benefit:'Residents reading a city budget need to distinguish service spending, capital projects and transfers before comparing headline totals.',
  scope:'Use Bozeman’s FY26 adopted operating budget and its glossary. Select the general fund, water, wastewater, solid waste and street-related fund or the closest explicitly named equivalents. Trace reported totals to their definitions and note where interfund transfers would be counted twice.',
  sources:[['https://www.bozemanmt.gov/departments/finance/budget-and-financial-reports','FY26 adopted budget, financial reports and capital-plan links']],
  first:'Pin the adopted budget edition and trace the general fund’s reported total to its source table. Record whether transfers and capital costs are included or unresolved.',
  output:'Five fund-definition records, a source-linked glossary and a worked example of one supported comparison or explicit double-counting limitation.',
  criteria:['Keep adopted, proposed and amended budgets distinct, with fiscal-year boundaries.','Do not treat revenues, expenditures, appropriations and cash balances as interchangeable.','No unsupported net-total calculation, fiscal-solvency rating or political judgment.']},
 {id:'5e1ce477-226a-41c2-9452-0b5ceefe056f',category:'civic-public-information',title:'Separate tribal-government service links from federal agency referrals',
  benefit:'Public-library and community helpers need to route general questions without confusing a sovereign tribal government with a federal office.',
  scope:'Starting with BIA’s official directory, locate public government websites for the Blackfeet Nation, Crow Tribe and Northern Cheyenne Tribe. Compare general-government, enrollment-information and community-service starting pages with BIA’s role. Index offices and official links, not individual leaders or private membership records.',
  sources:[['https://www.bia.gov/','Tribal Leaders Directory and agency-service context; follow official tribal website links']],
  first:'Confirm one official tribal website through the directory and record its general-government and enrollment-information routes, distinguishing them from BIA contacts.',
  output:'A three-government public-link directory with provenance, a neutral jurisdiction note and unresolved referral questions.',
  criteria:['Do not imply BIA determines every tribal service or membership decision.','Use each government’s own names and published role descriptions.','No ancestry research, eligibility judgment, membership data or contact with offices.']},

 {id:'f4cecaac-4cf5-4958-8588-59f23c6cfb2c',category:'open-data',title:'Prepare a documented food-access data slice for three Montana counties',
  benefit:'Community food planners need a reusable extract that does not mistake an older access measure for today’s store inventory.',
  scope:'Use the current USDA Food Access Research Atlas download for Silver Bow, Deer Lodge and Powell counties. Pin data vintage and tract geography before extracting low-income and distance-based food-access fields. Preserve tract identifiers and the urban/rural threshold definitions.',
  sources:[['https://www.ers.usda.gov/data-products/food-access-research-atlas/download-the-data','Official machine-readable download and documentation links'],['https://www.ers.usda.gov/data-products/food-access-research-atlas','Product scope and revision context']],
  first:'Read the data dictionary, identify the geographic vintage and extract one tract from Silver Bow County with two correctly defined access fields.',
  output:'A three-county tract extract with field dictionary, provenance, missingness notes and a clear historical-data limitation.',
  criteria:['Keep tract IDs as text and do not silently join different Census vintages.','Retain each distance threshold and urban/rural definition.','Do not identify individual households or claim current food-store availability from historical measures.']},
 {id:'b4d69a2b-a703-41c1-9dc7-963af338f3e0',category:'open-data',title:'Separate broadband availability from adoption in a rural-county data guide',
  benefit:'Digital-inclusion groups need to know which public measures describe offered service and which describe household use.',
  scope:'Use FCC Broadband Data Collection documentation and Census ACS internet-subscription documentation. Build a field/source guide for Beaverhead County, Montana, without downloading residential address points. Identify reporting dates, geographic units, provider-reported availability and household survey estimates; do not blend them into a single percentage.',
  sources:[['https://www.fcc.gov/BroadbandData','Availability data, releases and public download documentation'],['https://www.census.gov/programs-surveys/acs','ACS data documentation and computer/internet subscription tables']],
  first:'Locate one availability definition and one subscription definition. Record their dates, populations and geographic units, then explain why they are not interchangeable.',
  output:'A county-focused metadata crosswalk, reproducible public aggregate-query starting points and a no-invalid-join checklist.',
  criteria:['Availability is not adoption, affordability, experienced speed or reliable indoor coverage.','No individual address/fabric data, challenges, accounts or household profiling.','Keep survey uncertainty and provider-reporting limitations visible.']},
 {id:'4d0407cd-57e6-40e3-bfa5-366e8d40a2d9',category:'open-data',title:'Build a comparable rural-transit service extract from the 2024 NTD',
  benefit:'Rural mobility advocates need service measures that do not double-count operators or confuse passenger trips with unique riders.',
  scope:'Select the first five Montana rural reporters by NTD identifier in the 2024 annual data. Match agency information to vehicle revenue miles, vehicle revenue hours, unlinked trips and operating expense fields. Preserve mode, type of service and reporting-period qualifications.',
  sources:[['https://www.transit.dot.gov/ntd/ntd-data','2024 annual agency and service data products'],['https://www.transit.dot.gov/ntd','NTD metric definitions and reporting context']],
  first:'Pin the five-reporter sample and join one agency’s identifier to one service row, showing the mode/type-of-service key and units.',
  output:'A five-reporter extract with join keys, a data dictionary, totals only where valid and an explicit comparability note.',
  criteria:['Do not sum totals with their component rows or merge different service types without explanation.','Unlinked passenger trips are not unique people.','No fabricated service schedules, efficiency ranking or silent zero filling.']},
 {id:'29978940-9f78-48cd-9bc2-1f65f1089cea',category:'open-data',title:'Distinguish brownfield assessments from cleanup completion in public data',
  benefit:'Neighborhood reuse groups need to understand which milestones a public redevelopment record actually documents.',
  scope:'Use EPA ACRES public data for the first five Montana properties by stable property identifier. Extract assessment, cleanup and redevelopment milestone fields and their definitions. Work only with public project metadata; do not infer contamination status or property safety.',
  sources:[['https://www.epa.gov/brownfields/acres-frequently-asked-questions','ACRES scope and milestone meanings'],['https://catalog.data.gov/dataset/acres-brownfields-properties','Public dataset and publisher/download links']],
  first:'Locate the dataset and dictionary, pin the sample and annotate one property’s assessment versus cleanup fields with the exact published definitions.',
  output:'Five milestone records, data dictionary and a short explanation of unsupported conclusions the dataset cannot establish.',
  criteria:['Grant award, assessment, cleanup completion and redevelopment are distinct milestones.','Do not interpret a blank field as no contamination or no work.','No individual-owner profiling, property valuation or safety certification.']},
 {id:'649decdf-4ac7-4713-ba01-658f0fe5015f',category:'open-data',title:'Create a disability-estimate extract that keeps margins of error attached',
  benefit:'Community accessibility planners need county estimates with their populations and uncertainty visible.',
  scope:'Use one documented ACS five-year S1810 release for Silver Bow, Deer Lodge and Powell counties, selecting the newest release available on September 9, 2026. Extract overall disability estimates, denominators, percentages and corresponding margins of error. Do not mix one-year and five-year products.',
  sources:[['https://data.census.gov/table/ACSST5Y2023.S1810','Known five-year table entry; locate and pin the selected newer release if available'],['https://www.census.gov/programs-surveys/acs','ACS definitions, release documentation and uncertainty guidance']],
  first:'Pin the release and complete one county’s total estimate, denominator and matched margin-of-error fields with their variable identifiers.',
  output:'A three-county extract, variable dictionary and plain-language uncertainty note for reuse in accessibility planning.',
  criteria:['Use the same release, geography and population universe in every row.','Do not sum overlapping disability types or rank counties without a valid uncertainty comparison.','Aggregate data only; no inference about an individual resident’s disability.']},

 {id:'12533bd6-4f45-4428-a06b-5b4d1873e7e8',category:'consumer-protection',title:'Make broadband labels comparable without hiding introductory-price limits',
  benefit:'Community digital navigators need a transparent worksheet for comparing public internet offers without entering a resident’s address.',
  scope:'Use current FCC broadband-label guidance and three publicly viewable residential offers from AT&T, Xfinity and Google Fiber. Pin each offer’s stated market and date. Compare recurring price, introduction period, one-time costs, equipment and usage-related charges; stop at a public-information barrier instead of starting checkout.',
  sources:[['https://www.fcc.gov/broadbandlabels','Current consumer-label guidance and examples; direct automated retrieval may be restricted'],['https://www.fcc.gov/','Locate the current Glossary of Terms Used for Consumer Broadband Labels and any revisions']],
  first:'Verify the current FCC field definitions and locate one public provider label. Return a dated row with promotional and standard-price fields kept separate, or the exact access limitation.',
  output:'Three source-linked offer rows and a blank reusable comparison worksheet; unresolved prices remain unknown.',
  criteria:['Do not assume an offer is available at any reader’s address or select a recommended provider.','Separate monthly, one-time, usage-based and optional charges without inventing an all-in price.','No addresses, credit checks, purchases, accounts, calls or checkout interaction.']},
 {id:'6d5a1456-d104-43a5-ae6a-e89542501f36',category:'consumer-protection',title:'Separate airline refunds from meals, hotels and other service commitments',
  benefit:'Travel-assistance volunteers need to distinguish refund guidance from airline-specific commitments during disruptions.',
  scope:'Compare DOT refund guidance with its cancellation/delay dashboard for American, Delta and Southwest. Build five clearly fictional scenarios covering an airline cancellation, significant change, passenger cancellation, accepted alternative travel and a controllable delay. Record only what the current sources support.',
  sources:[['https://www.transportation.gov/individuals/aviation-consumer-protection/refunds','Official refund guidance and qualifications'],['https://www.transportation.gov/airconsumer/airline-cancellation-delay-dashboard','Carrier commitments and controllable-disruption scope']],
  first:'Map the airline-cancellation scenario to refund guidance and separately record one carrier’s meal/hotel commitment with its conditions.',
  output:'A five-scenario evidence matrix and an original neutral handout that distinguishes rights guidance from voluntary service commitments.',
  criteria:['Keep refunds, credits, rebooking and amenities separate.','Do not promise compensation or decide a real traveler’s entitlement.','Pin dates and conditions; no claims, bookings or personal itineraries.']},
 {id:'91ef0000-cf7b-4943-bf87-d7c79b892d2d',category:'consumer-protection',title:'Explain used-car warranty fields with clearly labeled practice examples',
  benefit:'Adult-education and consumer-help volunteers need to explain a Buyers Guide without conflating a warranty with a service contract.',
  scope:'Compare the FTC Buyers Guide and its dealer guidance for five concepts: as-is wording, dealer warranty, systems covered, duration and service contracts. Create three original fictional examples showing which fields a reader should inspect; do not copy a dealership listing or assess a purchase.',
  sources:[['https://www.ftc.gov/system/files/documents/plain-language/cfr_buyers_guides_english.pdf','Official English Buyers Guide field labels'],['https://www.ftc.gov/business-guidance/resources/dealers-guide-used-car-rule','Definitions, warranty changes and service-contract distinctions']],
  first:'Trace dealer-warranty and service-contract distinctions to the guidance, then draft one fictional annotated example without a real VIN or seller.',
  output:'A five-concept glossary, three practice examples and an evidence-linked note on state-specific questions that remain outside the exercise.',
  criteria:['Do not claim federal guidance resolves every state-law warranty question.','Mark every example as fictional and separate dealer, manufacturer and service-contract coverage.','No legal determination, vehicle recommendation, seller accusation or private transaction data.']},
 {id:'fda89f07-214b-45cc-ab88-f68af5f2eef7',category:'consumer-protection',title:'Trace repair-warranty claims back to FTC case records',
  benefit:'Repair advocates need to distinguish a consumer-alert summary, an allegation, a proposed settlement and a final order before quoting a case.',
  scope:'Take the first two companies named in the FTC’s July 7, 2022 warranty-restriction alert. Follow official case links and identify the complaint, proposed order and final disposition if published. Extract the actual repair-restriction issue without generalizing the case to every warranty dispute.',
  sources:[['https://consumer.ftc.gov/consumer-alerts/2022/07/ftc-says-companies-warranty-restrictions-were-illegal','Dated alert and linked official case materials'],['https://www.ftc.gov/business-guidance/blog/2019/03/nixing-fix-warranties-mag-moss-restrictions-repairs','Background explanation; distinguish its date and legal scope']],
  first:'Pin the two-case sample and locate one case’s complaint and order status. Return a document timeline with allegations clearly distinguished from findings or obligations.',
  output:'Two primary-record case timelines and a short, qualified summary suitable for a repair-rights reference page.',
  criteria:['Do not call a proposed settlement final without the final record.','Keep case-specific conduct, remedies and exceptions attached to their sources.','Historical research only; no individualized legal advice, complaint submission or accusations beyond the public record.']},
 {id:'a4214a14-a656-46f7-9405-275984ac663b',category:'consumer-protection',title:'Build an interstate-moving document checklist that separates brokers from movers',
  benefit:'People assisting a household move need to know which party and document each official consumer-protection instruction concerns.',
  scope:'Use FMCSA’s Protect Your Move materials to map five document types: estimate, order for service, bill of lading, inventory and rights booklet. Record who supplies each, its stated purpose and which broker-versus-carrier distinctions matter. Do not assess a specific mover.',
  sources:[['https://www.fmcsa.dot.gov/protect-your-move','Official rights booklet, moving checklist and broker/mover explanations']],
  first:'Trace estimate and bill-of-lading definitions to the current booklet. Draft two original checklist entries with the responsible party and source page.',
  output:'A five-document evidence map and a blank consumer checklist with explicit interstate scope and unresolved state/local questions.',
  criteria:['Keep broker and transporting carrier roles distinct.','Do not extend interstate guidance to all intrastate moves or promise recovery of money.','No mover rankings, registration lookups involving private customers, complaints or bookings.']},

 {id:'dca7881d-3ac9-48eb-accd-0dfbf0688c65',category:'infrastructure',title:'Explain bridge-condition records without labeling bridges unsafe',
  benefit:'Residents reviewing infrastructure priorities need to understand condition ratings, inspection dates and the limits of a national inventory.',
  scope:'Use the 2025 FHWA National Bridge Inventory for the first five highway bridges in Silver Bow County by structure number. Extract component ratings, inspection-date fields and the source’s condition classification. Explain what the file does not establish about current restrictions or safety.',
  sources:[['https://www.fhwa.dot.gov/bridge/nbi/ascii2025.cfm','2025 state data files and coding-guide links'],['https://www.fhwa.dot.gov/bridge/britab.cfm','Condition classification and table definitions']],
  first:'Verify the state/county codes and sample, then trace one bridge’s component ratings to the published summary-condition rule.',
  output:'Five dated inventory records, a rating glossary and a clear distinction between historical condition data and current official restrictions.',
  criteria:['Pin the schema/edition and preserve structure IDs and inspection dates.','Poor condition is not a standalone declaration that a bridge is unsafe or closed.','No vulnerability ranking, structural diagnosis, route advice or field inspection.']},
 {id:'ceb47176-8048-4c32-b68e-d14e7f7a0145',category:'infrastructure',title:'Clarify what New Orleans pumping-dashboard totals actually measure',
  benefit:'Residents reading stormwater updates need to distinguish pump counts, power capacity and readiness statements before interpreting a headline.',
  scope:'Compare SWBNO’s current Pumping and Power Dashboard with its drainage-system overview. Extract metric names, units, timestamps and inclusion rules. Create an original glossary explaining why a count of pumps or power capacity alone does not predict protection from a particular storm.',
  sources:[['https://www.swbno.org/Projects/PumpingandPower','Published dashboard metrics and power-system qualifications'],['https://www.swbno.org/Stormwater/Overview','Drainage system context and metric definitions']],
  first:'Trace one pump-count metric and one power-capacity metric to their definitions, recording units and update times without combining them.',
  output:'A six-metric glossary or all metrics if fewer, source comparison and a short limitations note for public reuse.',
  criteria:['Separate drainage pumps, constant-duty pumps and electrical capacity where the source does.','Do not infer live reliability, flood protection or a neighborhood’s vulnerability.','No control-system access, operational instructions or unsupported equipment-status claims.']},
 {id:'be7bd926-0fd1-4316-9321-89cb17660257',category:'infrastructure',title:'Compare weekend transit-service information in Butte, Helena and Missoula',
  benefit:'Residents without cars need to see the published service limits and booking requirements before relying on a weekend trip.',
  scope:'Compare official fixed-route and demand-response information for Butte’s TheBus, Helena’s Capital Transit and Missoula’s Mountain Line. Extract Saturday/Sunday service statements, reservation requirements and holiday exceptions. Do not create a door-to-door itinerary or assume one service type’s rules apply to another.',
  sources:[['https://www.co.silverbow.mt.us/','Locate the official public-transit/TheBus schedules'],['https://www.helenamt.gov/','Locate Capital Transit routes and demand-response information'],['https://mountainline.com/','Official service schedules and rider guidance']],
  first:'Complete one agency’s weekend row, separating fixed-route schedules from any demand-response booking rules and noting the timetable edition.',
  output:'A three-agency weekend-service comparison with current schedule links, edition dates and unresolved rider questions.',
  criteria:['Published schedules are not live vehicle availability.','Keep weekday, weekend, holiday and reservation conditions separate.','No trip booking, calls, private rider data or guaranteed accessible route.'],minutes:10},
 {id:'b9966f54-4763-4b7b-8422-8cfb3c9dfbba',category:'infrastructure',title:'Distinguish planned, funded and completed Durham sidewalk projects',
  benefit:'Neighborhood groups need to know whether a project is an idea, a funded commitment or documented construction progress.',
  scope:'Use Durham’s current city Capital Improvement Plan and linked project pages. Select the first three sidewalk-related projects alphabetically by published title. Trace project identifiers, funding-year entries and explicitly documented delivery status without inferring completion from budget allocation.',
  sources:[['https://www.durhamnc.gov/223/Capital-Improvement-Plan-CIP','City CIP, project descriptions and linked budgets/status pages']],
  first:'Pin the plan edition and three-project sample. Trace one project’s budget line to a current status page or record that no matching status page was found.',
  output:'A three-project funding/status crosswalk with dated evidence and a glossary of the status terms actually used.',
  criteria:['Keep the City of Durham separate from Durham County.','An appropriation, design contract or planned year is not proof of completed construction.','No site visits, route safety ratings, spending allegations or unsupported schedule promises.']},
 {id:'295962cd-a821-4a9b-9f62-aec61314f9e3',category:'infrastructure',title:'Match Washington ferry alerts to the right published route schedules',
  benefit:'Island residents and community travel helpers need to distinguish route-specific service notices from system-wide information.',
  scope:'Compare official alerts and schedules for Seattle–Bainbridge, Edmonds–Kingston and Mukilteo–Clinton. Pin a retrieval timestamp and schedule season. Classify each relevant notice by route, sailing/date scope and vehicle versus walk-on implications only where explicitly stated.',
  sources:[['https://wsdot.com/ferries/schedule/bulletin.aspx','Time-sensitive official alert bulletins'],['https://wsdot.wa.gov/travel/washington-state-ferries/schedules','Official schedules, seasons and route links']],
  first:'Complete the Seattle–Bainbridge row with its schedule edition and one relevant notice or a timestamped no-notice-found result.',
  output:'Three route-to-alert records and a reusable checking checklist that links readers back to live official information.',
  criteria:['A system-wide bulletin may not affect every sailing; preserve route and date scope.','No notice found does not guarantee on-time service or boarding space.','No ticket purchases, reservations, live-availability promises or private travel details.'],minutes:10},

 {id:'a4b9e0af-fea2-449c-8642-ba7cd9709973',category:'humanitarian-public-interest-research',title:'Compare offline heating-assistance application routes in North Dakota and Kentucky',
  benefit:'Outreach volunteers need to help people find official assistance information without assuming they have reliable internet or a fixed mailing address.',
  scope:'Compare current ND and KY LIHEAP public instructions for paper, phone and in-person starting points, seasonal versus crisis assistance, documentation lists and any explicitly published mailing-address alternatives. Missing guidance should become a referral question, not a made-up workaround.',
  sources:[['https://www.hhs.nd.gov/applyforhelp/liheap','North Dakota program, application channels and assistance types'],['https://chfs.ky.gov/agencies/dcbs/dfs/pdb/Pages/liheap.aspx','Kentucky program and local application routes']],
  first:'Complete North Dakota’s offline-channel fields and identify whether the page explicitly addresses mailing-address alternatives or leaves that question unresolved.',
  output:'Two state-program comparison rows and a plain-language referral checklist with dated official links.',
  criteria:['Keep regular and crisis programs, application periods and local administration separate.','Do not infer eligibility, benefit amounts, open funding or acceptance of missing documents.','No applications, personal income/utility records, appointments or contact.']},
 {id:'d896d09a-4efc-4702-8266-6a7cfefe56f3',category:'humanitarian-public-interest-research',title:'Distinguish diaper-bank warehouses from places families can actually request help',
  benefit:'Parents and family-support volunteers need to avoid traveling to a donation warehouse that does not distribute directly to households.',
  scope:'Select the first three Kentucky members alphabetically in the National Diaper Bank Network directory, or all if fewer are listed. Follow each provider’s public assistance pages and distinguish direct distribution, partner-agency referrals, donation drop-offs and appointment requirements.',
  sources:[['https://nationaldiaperbanknetwork.org/member-directory/','Member-directory sample and official provider links'],['https://nationaldiaperbanknetwork.org/get-help-now/','Network help guidance and referral limitations']],
  first:'Pin the sample and complete one provider’s direct-versus-partner distribution row with the exact family-assistance link.',
  output:'Up to three verified referral records, a donation-versus-assistance distinction and unanswered access questions.',
  criteria:['Membership or a warehouse address does not establish walk-in household service.','Do not promise diaper sizes, inventory, eligibility or an appointment.','No parent/child details, assistance requests, calls or visits.'],minutes:10},
 {id:'e3aac649-bf16-4372-8ab6-974935e190ac',category:'humanitarian-public-interest-research',title:'Compare congregate and home-delivered meal referral information for older adults',
  benefit:'Caregivers need to distinguish community meal sites from home-delivery programs and their separate referral processes.',
  scope:'Use ACL’s nutrition guidance and official aging-network links for Silver Bow County, Montana; Cass County, North Dakota; and Jefferson County, Kentucky. Compare published congregate and home-delivered meal starting points, screening process, service boundaries and cost/donation wording.',
  sources:[['https://acl.gov/programs/health-wellness/nutrition-services','Federal nutrition-program context and aging-network referral links'],['https://www.usaging.org/older-adults-family-caregivers-eat-live-age-well','Program information and official Eldercare Locator starting point']],
  first:'Locate the official aging-network provider for one county and compare its two meal-service pathways, preserving unknown cost or screening details.',
  output:'Three county referral pairs with direct provider links, program distinctions and a short list of unresolved caregiver questions.',
  criteria:['Do not infer home-delivery eligibility from general congregate-meal age guidance.','Keep suggested donations distinct from required fees where sources distinguish them.','No health records, personal assessments, enrollments, meal orders or guaranteed availability.']},
 {id:'0825d242-0e9b-4346-905f-d89d0b7c85af',category:'humanitarian-public-interest-research',title:'Separate county counts from population exposure in maternity-care access reports',
  benefit:'Rural health advocates need to know whether a headline describes counties, residents or travel time before reusing it in community planning.',
  scope:'Use the current March of Dimes maternity-care-desert report and its Montana, North Dakota and Kentucky state profiles. Pin report editions, data years and classification definitions. Compare percent of counties, affected population measures and travel-access measures only where published.',
  sources:[['https://www.marchofdimes.org/maternity-care-deserts-report','Primary report, methodology and state-profile links'],['https://pmc.ncbi.nlm.nih.gov/articles/PMC12305214/','Published research on state-level prevalence and methodological context']],
  first:'Locate one state’s profile and extract two measures with their denominators and source years. Explain why they cannot be substituted for one another.',
  output:'Three state evidence rows and a methodology crosswalk separating geography, population and travel-access measures.',
  criteria:['Do not turn a share of counties into a share of residents.','Keep report vintage, provider/facility definitions and missing data explicit.','No individual care recommendations, facility rankings, current appointment claims or patient data.']},
 {id:'fa710f5e-e55d-4c0f-9b27-2831056eb4a7',category:'humanitarian-public-interest-research',title:'Clarify school-enrollment information for families without stable housing',
  benefit:'Family-support volunteers need a careful referral guide that distinguishes enrollment information from a requirement to produce every document first.',
  scope:'Compare NCHE’s July 2026 enrollment brief with Ohio’s official identification/eligibility/enrollment guidance. Trace the public roles of a local liaison, school-of-origin questions, records assistance and dispute-information links. Describe the sources; do not decide a child’s legal eligibility or school placement.',
  sources:[['https://nche.ed.gov/wp-content/uploads/2026/07/Enrolling_CYEH_In_School.pdf','Dated national enrollment brief and implementation qualifications'],['https://education.ohio.gov/Topics/Student-Supports/Homeless-Youth/Liaisons/Identification-Eligibility-and-Enrollment','Ohio’s official guidance and linked liaison resources']],
  first:'Compare the two sources on missing enrollment records and identify the official liaison referral route, with exact page or section references.',
  output:'A four-topic national/Ohio crosswalk and an original family-facing question sheet with official referral links.',
  criteria:['Keep federal explanation, Ohio procedure and local decisions distinct.','Do not promise transportation, placement or a dispute outcome.','No student names, housing histories, education records, applications or contacts.']},

 {id:'c8a28c54-5df0-4930-8989-3096a83515e2',category:'archival-historical-research',title:'Index historic Appalachian school records across drawings, photographs and histories',
  benefit:'Local-history volunteers need a reliable index showing which archival materials exist for the same historic school.',
  scope:'In the Library of Congress HABS/HAER/HALS collection, select five Kentucky or West Virginia school buildings documented as built before 1950, ordered by collection identifier. Index catalog metadata, historical drawings, photographs and written histories without reproducing whole files or modern security details.',
  sources:[['https://www.loc.gov/collections/historic-american-buildings-landscapes-and-engineering-records/about-this-collection/','Collection scope and catalog search; direct automated retrieval may be restricted']],
  first:'Pin the sample and complete one school’s catalog-to-material index, distinguishing construction date from documentation date.',
  output:'Five archival record groups with stable identifiers, material availability, rights notes and unresolved metadata conflicts.',
  criteria:['Use stable catalog IDs and keep building dates separate from survey/photo dates.','An absent digital item does not prove the archive lacks the original.','No modern security-layout extraction, personal school records or unsupported rights claims.']},
 {id:'1fb726f9-2aa8-4b52-a90f-85c1c602256e',category:'archival-historical-research',title:'Match Butte Sanborn map editions without confusing sheet numbers',
  benefit:'Neighborhood historians need to compare the same area across map editions without treating a sheet number as a permanent location identifier.',
  scope:'Use Library of Congress catalog records for Butte’s 1891, 1900 and 1916 Sanborn editions, verifying availability first. Trace the Main Street–Granite Street intersection through each edition’s index and record the relevant sheet or sheets. Do not interpret historical mapping as a current property condition.',
  sources:[['https://www.loc.gov/item/sanborn04950_005/','Butte 1900 catalog record and digitized-sheet links'],['https://guides.loc.gov/fire-insurance-maps/sanborn-searching','Collection searching, editions and indexes']],
  first:'Confirm the 1900 edition metadata and identify the sheet covering the named intersection, with the index evidence and stable item/sheet link.',
  output:'A three-edition sheet crosswalk, catalog provenance and a short note on changed numbering or incomplete digitization.',
  criteria:['Verify all edition dates; mark an unavailable edition rather than substituting silently.','Use index evidence instead of assuming the same sheet number covers the same area.','No current ownership, environmental-safety or building-condition conclusions.']},
 {id:'f31a0120-3942-4f9a-88a9-099adc7773ab',category:'archival-historical-research',title:'Trace 1918 influenza newspaper claims back to their printed pages',
  benefit:'History educators need citations that distinguish what a newspaper reported at the time from established historical conclusions.',
  scope:'Select the first three U.S. newspaper items chronologically in the Library of Congress influenza guide’s selected articles. Verify newspaper title, date, page and column against page images. Compare one public-meeting or school-closure statement per item with its wording and attribution.',
  sources:[['https://guides.loc.gov/chronicling-america-spanish-flu/selected-articles','Curated historic newspaper items and page links'],['https://guides.loc.gov/chronicling-america-spanish-flu','Historical research context and terminology']],
  first:'Pin the sample and verify one article’s page/column citation, recording whether its closure statement is attributed to an official or merely reported.',
  output:'Three checked citations, original short summaries and a note on contemporary reporting uncertainty or OCR errors.',
  criteria:['Check page images when accessible; label OCR-only work explicitly.','Keep historical terminology contextualized and avoid presenting period health claims as current medical guidance.','Do not reproduce whole articles or invent corroboration from a second source.']},
 {id:'6febcd4c-515c-4e58-bd4c-20fe6963f51f',category:'archival-historical-research',title:'Create a source-and-bias index for WPA coal-mining life histories',
  benefit:'Community historians need to distinguish interview testimony, interviewer editing and catalog description when reusing working-life accounts.',
  scope:'From the Library of Congress Federal Writers’ Project collection, select five U.S. coal-mining-related life histories, ordered by catalog identifier. Record interview/document dates, interviewer attribution, location at county/state level, transcript availability and editorial qualifications.',
  sources:[['https://www.loc.gov/collections/federal-writers-project/about-this-collection/','Collection description, editorial context and catalog; direct automated retrieval may be restricted']],
  first:'Locate one relevant record and separate what its catalog states from what the transcript itself supports. Return an evidence-linked metadata row and one source-bias note.',
  output:'Five catalog/transcript records and an original researcher note on interviewer mediation, selection limits and respectful quotation.',
  criteria:['Do not treat recollection as independent proof of every event or reconstruct missing speech.','Retain dialect and offensive historical wording only when essential and clearly contextualized; do not normalize it as current language.','No living-person genealogy, unsupported rights assertions or wholesale transcription.']},
 {id:'fba43a61-ffb1-4cf6-8ac3-4cb0fdc03721',category:'archival-historical-research',title:'Build a provenance guide to federal Cherokee-removal record series',
  benefit:'Public-history researchers need a clear path through federal record descriptions without mistaking administrative categories for the full experience of removal.',
  scope:'Use NARA’s Cherokee-removal guide to index the first five listed relevant microfilm publications or record series. Record publication/series identifier, date range, creating office, digitization status and what the guide says the records contain. Keep this at series level, not individual ancestry research.',
  sources:[['https://www.archives.gov/research/native-americans/cherokee-removal','Primary archival guide to 1836–1839 removal records'],['https://www.archives.gov/research/native-americans/rolls','Context and limitations of federal rolls and related records']],
  first:'Pin the five-series sample and complete one record’s creating-office, date-range and access fields, distinguishing a finding aid from digitized records.',
  output:'Five archival access/provenance records and a respectful note about administrative perspective and missing voices.',
  criteria:['Use exact archive identifiers and do not equate a catalog listing with complete online access.','Explain period administrative labels without endorsing them.','No individual membership, ancestry or eligibility claims and no reconstruction of missing records.']},

 {id:'d3430db8-7063-405d-858c-c5b7e515fa24',category:'verification-and-fact-checking',title:'Check national crime-change claims against counts, rates and reporting scope',
  benefit:'Community-news readers need to know whether a reported change concerns estimated offenses, rates or participating agencies.',
  scope:'Take three quantitative change statements from the FBI’s 2024 reported-crime release and trace them to the underlying official summary and methodology. Compare the metric, denominator, coverage and revision year. Do not create city rankings or infer causes.',
  sources:[['https://www.fbi.gov/news/press-releases/fbi-releases-2024-reported-crimes-in-the-nation-statistics','Dated release and quantitative statements'],['https://www.fbi.gov/how-we-can-help-you/more-fbi-services-and-information/ucr','UCR scope, participation context and official report links']],
  first:'Select the three statements and verify one against its source table, distinguishing estimated count change from change in a population-normalized rate.',
  output:'A three-claim verification table with exact source rows, calculations if supported, and qualified verdicts.',
  criteria:['Keep offense definitions, estimates, reports and population denominators distinct.','Do not interpret reporting gaps as zero crime or assign a cause to a descriptive change.','No neighborhood targeting, demographic blame, individual records or misleading safety rankings.']},
 {id:'a16e5d4b-8896-485d-840a-29e2829365e3',category:'verification-and-fact-checking',title:'Verify housing-vacancy claims without mixing different housing inventories',
  benefit:'Housing advocates need to distinguish vacant-for-rent, vacant-for-sale and all vacant units before reusing a headline percentage.',
  scope:'Use the Census Q2 2026 Housing Vacancies and Homeownership release and linked definitions. Trace rental vacancy, homeowner vacancy and total vacant-unit quantities to their denominators. Check whether one reported year-over-year comparison is described as statistically different.',
  sources:[['https://www.census.gov/housing/hvs/current/index.html','Current release; locate and pin Q2 2026 before extracting'],['https://www.census.gov/housing/hvs/','Definitions, methodology and historical releases']],
  first:'Pin Q2 2026 and document rental versus homeowner vacancy definitions and denominators with exact table references.',
  output:'Three measure-definition checks, one uncertainty-aware comparison and an original caution against misleading vacancy arithmetic.',
  criteria:['Do not add rates with different denominators or equate seasonal units with housing offered for occupancy.','Preserve statistical-significance wording and survey uncertainty.','No property valuation, investment advice or claim about a particular neighborhood’s available homes.']},
 {id:'0bc1b853-4c0e-4763-9e84-014855b049f7',category:'verification-and-fact-checking',title:'Trace widely repeated U.S. food-waste figures to their original scope',
  benefit:'Food-recovery groups need statistics with the original year, measurement basis and supply-chain stage attached.',
  scope:'Use USDA’s Food Waste FAQs and the original estimates it links. Verify the frequently repeated percentage of the food supply, pounds of loss and estimated value. Record whether each concerns retail/consumer loss, other supply-chain stages, physical mass or economic value.',
  sources:[['https://www.usda.gov/about-food/food-safety/food-loss-and-waste/food-waste-faqs','Official FAQ and links to original estimates']],
  first:'Trace the percentage estimate to its cited source and year. Return one claim record identifying its denominator and the limits on calling it a current measurement.',
  output:'A three-figure provenance table and three original, accurately qualified replacement sentences for community reports.',
  criteria:['Do not treat a recently updated webpage as proof that the underlying estimate is recent.','Do not equate food loss, edible avoidable waste and landfill tonnage without source support.','No invented inflation adjustment, unsupported annual extrapolation or claim that all lost food could be redistributed.']},
 {id:'66f89a1f-71d6-472a-83c2-c6535c70dfc0',category:'verification-and-fact-checking',title:'Reconcile school-spending headlines with current-spending and total-expenditure tables',
  benefit:'Parents and local reporters need to know what a per-pupil figure includes before comparing it with a district’s total budget.',
  scope:'Use the Census FY2024 school-finance release and tables for Montana, North Dakota and Kentucky. Compare current spending per pupil with total expenditure, capital outlay and enrollment definitions. Keep preliminary and final tables separate and do not rank school quality.',
  sources:[['https://www.census.gov/newsroom/press-releases/2026/school-system-finances.html','May 2026 release and headline metric'],['https://www.census.gov/programs-surveys/school-finances.html','FY2024 tables, definitions and revision notes']],
  first:'Locate Montana’s final FY2024 row and identify the denominator and excluded costs for current spending per pupil.',
  output:'Three state metric crosswalks and a source-linked explanation of one misleading comparison to avoid.',
  criteria:['Do not divide total expenditure by a different enrollment measure and label it the published current-spending figure.','State whether dollars are nominal; do not imply inflation-adjusted growth without a documented deflator.','No school-performance inference or fiscal-misconduct allegation from spending alone.']},
 {id:'6be445ac-defe-4763-b8e7-65078d2fb9f4',category:'verification-and-fact-checking',title:'Check renewable-energy shares without confusing electricity with all energy use',
  benefit:'Community educators need energy statistics that retain their denominators and generation-accounting boundaries.',
  scope:'Use EIA’s U.S. energy and electricity explanations to locate one common complete year with both datasets. Compare renewable shares of electricity generation and total primary energy consumption, recording treatment of small-scale solar and relevant accounting notes.',
  sources:[['https://www.eia.gov/energyexplained/us-energy-facts/','Primary/secondary energy definitions and annual data links'],['https://www.eia.gov/energyexplained/electricity/','Electricity generation scope and source tables']],
  first:'Pin the common year and one denominator for each statistic. Return two source-linked definition rows before calculating any shares.',
  output:'Two verified share calculations or published-value checks, a scope comparison and four original correctly qualified statements.',
  criteria:['Do not present electricity share as a share of all energy consumed.','Keep units, small-scale generation treatment and accounting methods explicit.','No policy endorsement, emissions inference or claim about data-center benefits.']},

 {id:'f0e2a0e3-517a-4da6-a74d-da41e5fb7180',category:'useful-open-source-public-resource-work',title:'Prepare a text-description pack for five Smithsonian open-access objects',
  benefit:'Volunteer educators and accessible-catalog builders need concise original descriptions tied to clearly reusable object images.',
  scope:'Select five Smithsonian CC0-marked images of everyday historical household objects, ordered by stable object identifier. Inspect the images and separate visible description from catalog facts. Create short alternative-text drafts plus longer descriptions where necessary; do not infer details from an image you cannot view.',
  sources:[['https://www.si.edu/openaccess','Open-access object discovery'],['https://www.si.edu/openaccess/faq','CC0 markers, reuse scope and other-rights qualifications']],
  first:'Verify one object’s CC0 asset marker, inspect its image and draft a short original description. Cite the object ID and distinguish visual observation from catalog attribution.',
  output:'Five object records containing asset rights, source links, original short/long descriptions and uncertainty notes.',
  criteria:['A reusable catalog record does not automatically make every associated image CC0; verify each asset.','Do not guess race, disability, material, maker or date from appearance.','No upstream edits or claimed accessibility testing; if images cannot be inspected, return metadata evidence and the specific blocker.']},
 {id:'782f1e6c-c47c-4afd-8859-087827f6bb1c',category:'useful-open-source-public-resource-work',title:'Draft an OpenRefine import note that protects public-service identifiers',
  benefit:'Community-data volunteers need to preserve leading zeros, non-English names and blank fields when cleaning service-directory files.',
  scope:'Inspect current OpenRefine import documentation and source-linked documentation contribution guidance. Draft a small documentation addition or identify an adequate existing section covering identifier preservation, encoding and blank-versus-missing values. Use a tiny clearly fictional service-directory example, not real client records.',
  sources:[['https://openrefine.org/docs/manual/starting','Current parsing options, preview workflow and documentation links'],['https://github.com/OpenRefine/OpenRefine','Current project source, documentation contribution guidance and license']],
  first:'Pin the documentation version and identify the exact existing parsing guidance for leading-zero identifiers. Draft one minimal clarification only if a concrete gap remains.',
  output:'A source-pinned documentation patch or existing-resource finding, a four-row fictional example and manual verification cases marked unrun.',
  criteria:['Do not invent a UI option or claim an import was tested without execution.','Keep the example obviously fictional and identifiers represented as text.','No software installation, downloaded-code execution, upstream issue/PR or external edits; retain upstream license requirements.'],code:true},
 {id:'9c94144b-d9dd-43af-8a28-9f452006665b',category:'useful-open-source-public-resource-work',title:'Build a low-bandwidth classic-reading index for U.S. community libraries',
  benefit:'Volunteer reading groups need direct, reusable text-format links and honest rights notes instead of pages that require accounts or proprietary apps.',
  scope:'Choose five short English-language works in Project Gutenberg suitable for an adult community reading group. Record stable ebook IDs, title/author, available plain-text and EPUB links, length basis and the individual rights notice. Include brief original content notes without reproducing the works.',
  sources:[['https://www.gutenberg.org/','Catalog and individual ebook format/rights records'],['https://www.gutenberg.org/policy/terms_of_use.html','Territorial copyright and usage qualifications']],
  first:'Select one work, verify its plain-text/EPUB links and item-specific rights notice, then write a short original note about discussion use and any sensitive historical content.',
  output:'A five-work text/EPUB index with stable identifiers, original content notes and U.S.-scope rights qualifications.',
  criteria:['Do not assume every work is unrestricted everywhere or remove required notices from copied material.','Label estimated reading length and explain its basis; do not invent a tested reading level.','No account creation, downloads of executable readers, paid recommendations or wholesale text copying.']},
 {id:'e14bf8f2-1b01-410e-b3f1-065c321fa1bd',category:'useful-open-source-public-resource-work',title:'Create a privacy-safe community-service directory worksheet using Open Referral',
  benefit:'Small mutual-aid groups need a reusable way to record public service information without collecting details about the people seeking help.',
  scope:'Use the current Open Referral HSDS documentation to draft a compact field worksheet covering organization, service, location, public phone, schedule, languages, eligibility text and source/update date. Show how fields map to HSDS, while clearly labeling the worksheet as a subset rather than a full compliant export.',
  sources:[['https://docs.openreferral.org/en/latest/hsds/overview.html','Current HSDS overview, schema entities and field documentation']],
  first:'Pin the specification version and map organization, service and location identifiers to three worksheet fields. Provide one clearly fictional example with no real personal details.',
  output:'A blank reusable worksheet, HSDS field crosswalk, one fictional example and a refresh/privacy checklist.',
  criteria:['Keep organization, service and service-location records distinct.','Do not claim full HSDS validation or interoperability for an unvalidated subset.','No client records, sensitive shelter locations, real personal phone numbers or external directory writes.']},
 {id:'2cba7b2a-3cf0-48d3-87f9-0fc569361c0f',category:'useful-open-source-public-resource-work',title:'Create a private-use emergency-contact worksheet that works without an app',
  benefit:'Community preparedness volunteers need an accessible blank handout that families can fill out privately and use offline.',
  scope:'Use Ready.gov’s family communication-plan guidance to create an original plain-text worksheet with household contacts, an out-of-area contact, meeting-place prompts and a last-reviewed date. Publish only blank fields and fictional examples; the completed plan is for private household use, never submission to a public board.',
  sources:[['https://www.ready.gov/plan','Official planning guidance and printable communication-plan links; direct automated retrieval may be restricted']],
  first:'Locate the current official communication-plan resource and draft the blank contact section with a prominent instruction to keep completed copies private.',
  output:'An original printable blank worksheet, source-linked field rationale and a short accessibility/privacy checklist.',
  criteria:['Never request or publish real names, numbers, addresses, health details or meeting locations.','Do not prescribe evacuation routes or emergency tactics beyond accurately attributed official planning prompts.','Use readable text labels rather than color or icons alone, and do not claim a completed safety plan or tested accessibility.'],minutes:10}
];
