import {recordOwnerVerification} from '@/lib/owner-verification';
import {archiveTask} from '@/lib/task-archive';
import {dispatchNotifications} from '@/lib/notifications';
import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {authorizeModerator,moderationQueue,moderate,acceptReviewed,removeContact,featureMission,moderateAgentContent} from '@/lib/moderation';
import {body,response,errorResponse,ApiError} from '@/lib/commons';
import {updateHandoff} from '@/lib/task-edit';
import {hideComment,moderateComment} from '@/lib/guest-board';
export async function GET(){try{authorizeModerator((await getChatGPTUser())?.email,env.MODERATOR_EMAIL);return response({data:await moderationQueue(env.DB)})}catch(e){return errorResponse(e)}}
export async function POST(r:Request){try{const owner=(await getChatGPTUser())?.email;authorizeModerator(owner,env.MODERATOR_EMAIL);if(r.headers.get('origin')!==new URL(r.url).origin)throw new ApiError(403,'ORIGIN_REJECTED','Same-origin moderator request required');const input=await body(r);if(input.action==='agent_content'){const {action,decision,...rest}=input;const value={...rest,action:decision};return response({data:await moderateAgentContent(env.DB,value,owner!)})}if(input.action==='owner-verification'){const {action,task_id,...value}=input;void action;return response({data:await recordOwnerVerification(env.DB,task_id,value,null)})}if(input.action==='archive'){const {action,task_id,...value}=input;return response({data:await archiveTask(env.DB,task_id,value,null)})}if(input.action==='handoff'){const {action,task_id,...value}=input;return response({data:await updateHandoff(env.DB,task_id,value,null)})}if(input.action==='feature'){const {action,...value}=input;return response({data:await featureMission(env.DB,value)})}if(input.action==='restore_comment')return response({data:await moderateComment(env.DB,{comment_id:input.comment_id,reason:input.reason,action:'restored'})});if(input.action==='hide_comment')return response({data:await hideComment(env.DB,{comment_id:input.comment_id,reason:input.reason})});if(input.action==='dispatch_email')return response({data:await dispatchNotifications(env.DB,env)});if(input.action==='remove_contact')return response({data:await removeContact(env.DB,{task_id:input.task_id})});if(input.action==='accept'){const {action,...value}=input;const accepted=await acceptReviewed(env.DB,value);await dispatchNotifications(env.DB,env);return response({data:accepted})}return response({data:await moderate(env.DB,input)})}catch(e){return errorResponse(e)}}
