/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=tests/fixtures/relay-scheduler-bindings.json --include-runtime=false --strict-vars=false --env-interface=RelaySchedulerBindings worker/relay-scheduler-bindings.d.ts` (hash: 6a121d8d5c9e71776cf54eef8b58f0cd)
interface __BaseEnv_RelaySchedulerBindings {
	RELAY_SHADOW_ENABLED: string;
	RELAY_SHADOW_SOURCE_VERSION: string;
	RELAY_SELF_HOSTED: string;
	MIGRATION_FREEZE: string;
	RELAY_OPERATOR_ENABLED: string;
	RELAY_RESOLUTION_ENABLED: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_RelaySchedulerBindings {}
}
interface RelaySchedulerBindings extends __BaseEnv_RelaySchedulerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RELAY_SHADOW_ENABLED" | "RELAY_SHADOW_SOURCE_VERSION" | "RELAY_SELF_HOSTED" | "MIGRATION_FREEZE" | "RELAY_OPERATOR_ENABLED" | "RELAY_RESOLUTION_ENABLED">> {}
}
