/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=tests/fixtures/relay-chat-bindings.json --include-runtime=false --strict-vars=false --env-interface=RelayChatBindings worker/relay-chat-bindings.d.ts` (hash: 71ba02617a2dd19633c643b1831a1564)
interface __BaseEnv_RelayChatBindings {
	RELAY_CHAT_ENABLED: string;
	RELAY_CHAT_IP_SECRET: string;
	MIGRATION_FREEZE: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_RelayChatBindings {}
}
interface RelayChatBindings extends __BaseEnv_RelayChatBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RELAY_CHAT_ENABLED" | "RELAY_CHAT_IP_SECRET" | "MIGRATION_FREEZE">> {}
}
